/*
 * QuickJS opcode definitions
 *
 * Copyright (c) 2017-2018 Fabrice Bellard
 * Copyright (c) 2017-2018 Charlie Gordon
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

// Direct translation of quickjs-opcode.h from QuickJS 2026-06-04.
define_opcode_tables! {
    final {
        Invalid => ("invalid", 1, 0, 0, None),
        PushI32 => ("push_i32", 5, 0, 1, I32),
        PushConst => ("push_const", 5, 0, 1, Const),
        FClosure => ("fclosure", 5, 0, 1, Const),
        PushAtomValue => ("push_atom_value", 5, 0, 1, Atom),
        PrivateSymbol => ("private_symbol", 5, 0, 1, Atom),
        Undefined => ("undefined", 1, 0, 1, None),
        Null => ("null", 1, 0, 1, None),
        PushThis => ("push_this", 1, 0, 1, None),
        PushFalse => ("push_false", 1, 0, 1, None),
        PushTrue => ("push_true", 1, 0, 1, None),
        Object => ("object", 1, 0, 1, None),
        SpecialObject => ("special_object", 2, 0, 1, U8),
        Rest => ("rest", 3, 0, 1, U16),
        Drop => ("drop", 1, 1, 0, None),
        Nip => ("nip", 1, 2, 1, None),
        Nip1 => ("nip1", 1, 3, 2, None),
        Dup => ("dup", 1, 1, 2, None),
        Dup1 => ("dup1", 1, 2, 3, None),
        Dup2 => ("dup2", 1, 2, 4, None),
        Dup3 => ("dup3", 1, 3, 6, None),
        Insert2 => ("insert2", 1, 2, 3, None),
        Insert3 => ("insert3", 1, 3, 4, None),
        Insert4 => ("insert4", 1, 4, 5, None),
        Perm3 => ("perm3", 1, 3, 3, None),
        Perm4 => ("perm4", 1, 4, 4, None),
        Perm5 => ("perm5", 1, 5, 5, None),
        Swap => ("swap", 1, 2, 2, None),
        Swap2 => ("swap2", 1, 4, 4, None),
        Rot3l => ("rot3l", 1, 3, 3, None),
        Rot3r => ("rot3r", 1, 3, 3, None),
        Rot4l => ("rot4l", 1, 4, 4, None),
        Rot5l => ("rot5l", 1, 5, 5, None),
        CallConstructor => ("call_constructor", 3, 2, 1, NPop),
        Call => ("call", 3, 1, 1, NPop),
        TailCall => ("tail_call", 3, 1, 0, NPop),
        CallMethod => ("call_method", 3, 2, 1, NPop),
        TailCallMethod => ("tail_call_method", 3, 2, 0, NPop),
        ArrayFrom => ("array_from", 3, 0, 1, NPop),
        Apply => ("apply", 3, 3, 1, U16),
        Return => ("return", 1, 1, 0, None),
        ReturnUndef => ("return_undef", 1, 0, 0, None),
        CheckCtorReturn => ("check_ctor_return", 1, 1, 2, None),
        CheckCtor => ("check_ctor", 1, 0, 0, None),
        InitCtor => ("init_ctor", 1, 0, 1, None),
        CheckBrand => ("check_brand", 1, 2, 2, None),
        AddBrand => ("add_brand", 1, 2, 0, None),
        ReturnAsync => ("return_async", 1, 1, 0, None),
        Throw => ("throw", 1, 1, 0, None),
        ThrowError => ("throw_error", 6, 0, 0, AtomU8),
        Eval => ("eval", 5, 1, 1, NPopU16),
        ApplyEval => ("apply_eval", 3, 2, 1, U16),
        RegExp => ("regexp", 1, 2, 1, None),
        GetSuper => ("get_super", 1, 1, 1, None),
        Import => ("import", 1, 2, 1, None),
        ImportDefer => ("import_defer", 1, 2, 1, None),
        GetVarUndef => ("get_var_undef", 3, 0, 1, VarRef),
        GetVar => ("get_var", 3, 0, 1, VarRef),
        PutVar => ("put_var", 3, 1, 0, VarRef),
        PutVarInit => ("put_var_init", 3, 1, 0, VarRef),
        GetRefValue => ("get_ref_value", 1, 2, 3, None),
        PutRefValue => ("put_ref_value", 1, 3, 0, None),
        GetField => ("get_field", 5, 1, 1, Atom),
        GetField2 => ("get_field2", 5, 1, 2, Atom),
        PutField => ("put_field", 5, 2, 0, Atom),
        GetPrivateField => ("get_private_field", 1, 2, 1, None),
        PutPrivateField => ("put_private_field", 1, 3, 0, None),
        DefinePrivateField => ("define_private_field", 2, 3, 1, U8),
        GetArrayEl => ("get_array_el", 1, 2, 1, None),
        GetArrayEl2 => ("get_array_el2", 1, 2, 2, None),
        GetArrayEl3 => ("get_array_el3", 1, 2, 3, None),
        PutArrayEl => ("put_array_el", 1, 3, 0, None),
        GetSuperValue => ("get_super_value", 1, 3, 1, None),
        PutSuperValue => ("put_super_value", 1, 4, 0, None),
        DefineField => ("define_field", 5, 2, 1, Atom),
        SetName => ("set_name", 5, 1, 1, Atom),
        SetNameComputed => ("set_name_computed", 1, 2, 2, None),
        SetProto => ("set_proto", 1, 2, 1, None),
        SetHomeObject => ("set_home_object", 1, 2, 2, None),
        DefineArrayEl => ("define_array_el", 1, 3, 2, None),
        Append => ("append", 1, 3, 2, None),
        CopyDataProperties => ("copy_data_properties", 2, 3, 3, U8),
        DefineMethod => ("define_method", 6, 2, 1, AtomU8),
        DefineMethodComputed => ("define_method_computed", 2, 3, 1, U8),
        DefineClass => ("define_class", 6, 2, 2, AtomU8),
        DefineClassComputed => ("define_class_computed", 6, 3, 3, AtomU8),
        GetLoc => ("get_loc", 3, 0, 1, Loc),
        PutLoc => ("put_loc", 3, 1, 0, Loc),
        SetLoc => ("set_loc", 3, 1, 1, Loc),
        GetArg => ("get_arg", 3, 0, 1, Arg),
        PutArg => ("put_arg", 3, 1, 0, Arg),
        SetArg => ("set_arg", 3, 1, 1, Arg),
        GetVarRef => ("get_var_ref", 3, 0, 1, VarRef),
        PutVarRef => ("put_var_ref", 3, 1, 0, VarRef),
        SetVarRef => ("set_var_ref", 3, 1, 1, VarRef),
        SetLocUninitialized => ("set_loc_uninitialized", 3, 0, 0, Loc),
        GetLocCheck => ("get_loc_check", 3, 0, 1, Loc),
        PutLocCheck => ("put_loc_check", 3, 1, 0, Loc),
        SetLocCheck => ("set_loc_check", 3, 1, 1, Loc),
        PutLocCheckInit => ("put_loc_check_init", 3, 1, 0, Loc),
        GetLocCheckThis => ("get_loc_checkthis", 3, 0, 1, Loc),
        GetVarRefCheck => ("get_var_ref_check", 3, 0, 1, VarRef),
        PutVarRefCheck => ("put_var_ref_check", 3, 1, 0, VarRef),
        PutVarRefCheckInit => ("put_var_ref_check_init", 3, 1, 0, VarRef),
        CloseLoc => ("close_loc", 3, 0, 0, Loc),
        IfFalse => ("if_false", 5, 1, 0, Label),
        IfTrue => ("if_true", 5, 1, 0, Label),
        Goto => ("goto", 5, 0, 0, Label),
        Catch => ("catch", 5, 0, 1, Label),
        Gosub => ("gosub", 5, 0, 0, Label),
        Ret => ("ret", 1, 1, 0, None),
        NipCatch => ("nip_catch", 1, 2, 1, None),
        ToObject => ("to_object", 1, 1, 1, None),
        ToPropKey => ("to_propkey", 1, 1, 1, None),
        WithGetVar => ("with_get_var", 10, 1, 0, AtomLabelU8),
        WithPutVar => ("with_put_var", 10, 2, 1, AtomLabelU8),
        WithDeleteVar => ("with_delete_var", 10, 1, 0, AtomLabelU8),
        WithMakeRef => ("with_make_ref", 10, 1, 0, AtomLabelU8),
        WithGetRef => ("with_get_ref", 10, 1, 0, AtomLabelU8),
        MakeLocRef => ("make_loc_ref", 7, 0, 2, AtomU16),
        MakeArgRef => ("make_arg_ref", 7, 0, 2, AtomU16),
        MakeVarRefRef => ("make_var_ref_ref", 7, 0, 2, AtomU16),
        MakeVarRef => ("make_var_ref", 5, 0, 2, Atom),
        ForInStart => ("for_in_start", 1, 1, 1, None),
        ForOfStart => ("for_of_start", 1, 1, 3, None),
        ForAwaitOfStart => ("for_await_of_start", 1, 1, 3, None),
        ForInNext => ("for_in_next", 1, 1, 3, None),
        ForOfNext => ("for_of_next", 2, 3, 5, U8),
        ForAwaitOfNext => ("for_await_of_next", 1, 3, 4, None),
        IteratorCheckObject => ("iterator_check_object", 1, 1, 1, None),
        IteratorGetValueDone => ("iterator_get_value_done", 1, 2, 3, None),
        IteratorClose => ("iterator_close", 1, 3, 0, None),
        IteratorNext => ("iterator_next", 1, 4, 4, None),
        IteratorCall => ("iterator_call", 2, 4, 5, U8),
        InitialYield => ("initial_yield", 1, 0, 0, None),
        Yield => ("yield", 1, 1, 2, None),
        YieldStar => ("yield_star", 1, 1, 2, None),
        AsyncYieldStar => ("async_yield_star", 1, 1, 2, None),
        Await => ("await", 1, 1, 1, None),
        Neg => ("neg", 1, 1, 1, None),
        Plus => ("plus", 1, 1, 1, None),
        Dec => ("dec", 1, 1, 1, None),
        Inc => ("inc", 1, 1, 1, None),
        PostDec => ("post_dec", 1, 1, 2, None),
        PostInc => ("post_inc", 1, 1, 2, None),
        DecLoc => ("dec_loc", 2, 0, 0, Loc8),
        IncLoc => ("inc_loc", 2, 0, 0, Loc8),
        AddLoc => ("add_loc", 2, 1, 0, Loc8),
        Not => ("not", 1, 1, 1, None),
        Lnot => ("lnot", 1, 1, 1, None),
        Typeof => ("typeof", 1, 1, 1, None),
        Delete => ("delete", 1, 2, 1, None),
        DeleteVar => ("delete_var", 5, 0, 1, Atom),
        Mul => ("mul", 1, 2, 1, None),
        Div => ("div", 1, 2, 1, None),
        Mod => ("mod", 1, 2, 1, None),
        Add => ("add", 1, 2, 1, None),
        Sub => ("sub", 1, 2, 1, None),
        Pow => ("pow", 1, 2, 1, None),
        Shl => ("shl", 1, 2, 1, None),
        Sar => ("sar", 1, 2, 1, None),
        Shr => ("shr", 1, 2, 1, None),
        Lt => ("lt", 1, 2, 1, None),
        Lte => ("lte", 1, 2, 1, None),
        Gt => ("gt", 1, 2, 1, None),
        Gte => ("gte", 1, 2, 1, None),
        InstanceOf => ("instanceof", 1, 2, 1, None),
        In => ("in", 1, 2, 1, None),
        Eq => ("eq", 1, 2, 1, None),
        Neq => ("neq", 1, 2, 1, None),
        StrictEq => ("strict_eq", 1, 2, 1, None),
        StrictNeq => ("strict_neq", 1, 2, 1, None),
        And => ("and", 1, 2, 1, None),
        Xor => ("xor", 1, 2, 1, None),
        Or => ("or", 1, 2, 1, None),
        IsUndefinedOrNull => ("is_undefined_or_null", 1, 1, 1, None),
        PrivateIn => ("private_in", 1, 2, 1, None),
        PushBigIntI32 => ("push_bigint_i32", 5, 0, 1, I32),
        Nop => ("nop", 1, 0, 0, None),
    }
    temporary {
        EnterScope => ("enter_scope", 3, 0, 0, U16),
        LeaveScope => ("leave_scope", 3, 0, 0, U16),
        Label => ("label", 5, 0, 0, Label),
        ScopeGetVarUndef => ("scope_get_var_undef", 7, 0, 1, AtomU16),
        ScopeGetVar => ("scope_get_var", 7, 0, 1, AtomU16),
        ScopePutVar => ("scope_put_var", 7, 1, 0, AtomU16),
        ScopeDeleteVar => ("scope_delete_var", 7, 0, 1, AtomU16),
        ScopeMakeRef => ("scope_make_ref", 11, 0, 2, AtomLabelU16),
        ScopeGetRef => ("scope_get_ref", 7, 0, 2, AtomU16),
        ScopePutVarInit => ("scope_put_var_init", 7, 0, 2, AtomU16),
        ScopeGetVarCheckThis => ("scope_get_var_checkthis", 7, 0, 1, AtomU16),
        ScopeGetPrivateField => ("scope_get_private_field", 7, 1, 1, AtomU16),
        ScopeGetPrivateField2 => ("scope_get_private_field2", 7, 1, 2, AtomU16),
        ScopePutPrivateField => ("scope_put_private_field", 7, 2, 0, AtomU16),
        ScopeInPrivateField => ("scope_in_private_field", 7, 1, 1, AtomU16),
        GetFieldOptChain => ("get_field_opt_chain", 5, 1, 1, Atom),
        GetArrayElOptChain => ("get_array_el_opt_chain", 1, 2, 1, None),
        SetClassName => ("set_class_name", 5, 1, 1, U32),
        LineNum => ("line_num", 5, 0, 0, U32),
    }
    short {
        PushMinus1 => ("push_minus1", 1, 0, 1, NoneInt),
        Push0 => ("push_0", 1, 0, 1, NoneInt),
        Push1 => ("push_1", 1, 0, 1, NoneInt),
        Push2 => ("push_2", 1, 0, 1, NoneInt),
        Push3 => ("push_3", 1, 0, 1, NoneInt),
        Push4 => ("push_4", 1, 0, 1, NoneInt),
        Push5 => ("push_5", 1, 0, 1, NoneInt),
        Push6 => ("push_6", 1, 0, 1, NoneInt),
        Push7 => ("push_7", 1, 0, 1, NoneInt),
        PushI8 => ("push_i8", 2, 0, 1, I8),
        PushI16 => ("push_i16", 3, 0, 1, I16),
        PushConst8 => ("push_const8", 2, 0, 1, Const8),
        FClosure8 => ("fclosure8", 2, 0, 1, Const8),
        PushEmptyString => ("push_empty_string", 1, 0, 1, None),
        GetLoc8 => ("get_loc8", 2, 0, 1, Loc8),
        PutLoc8 => ("put_loc8", 2, 1, 0, Loc8),
        SetLoc8 => ("set_loc8", 2, 1, 1, Loc8),
        GetLoc0 => ("get_loc0", 1, 0, 1, NoneLoc),
        GetLoc1 => ("get_loc1", 1, 0, 1, NoneLoc),
        GetLoc2 => ("get_loc2", 1, 0, 1, NoneLoc),
        GetLoc3 => ("get_loc3", 1, 0, 1, NoneLoc),
        PutLoc0 => ("put_loc0", 1, 1, 0, NoneLoc),
        PutLoc1 => ("put_loc1", 1, 1, 0, NoneLoc),
        PutLoc2 => ("put_loc2", 1, 1, 0, NoneLoc),
        PutLoc3 => ("put_loc3", 1, 1, 0, NoneLoc),
        SetLoc0 => ("set_loc0", 1, 1, 1, NoneLoc),
        SetLoc1 => ("set_loc1", 1, 1, 1, NoneLoc),
        SetLoc2 => ("set_loc2", 1, 1, 1, NoneLoc),
        SetLoc3 => ("set_loc3", 1, 1, 1, NoneLoc),
        GetArg0 => ("get_arg0", 1, 0, 1, NoneArg),
        GetArg1 => ("get_arg1", 1, 0, 1, NoneArg),
        GetArg2 => ("get_arg2", 1, 0, 1, NoneArg),
        GetArg3 => ("get_arg3", 1, 0, 1, NoneArg),
        PutArg0 => ("put_arg0", 1, 1, 0, NoneArg),
        PutArg1 => ("put_arg1", 1, 1, 0, NoneArg),
        PutArg2 => ("put_arg2", 1, 1, 0, NoneArg),
        PutArg3 => ("put_arg3", 1, 1, 0, NoneArg),
        SetArg0 => ("set_arg0", 1, 1, 1, NoneArg),
        SetArg1 => ("set_arg1", 1, 1, 1, NoneArg),
        SetArg2 => ("set_arg2", 1, 1, 1, NoneArg),
        SetArg3 => ("set_arg3", 1, 1, 1, NoneArg),
        GetVarRef0 => ("get_var_ref0", 1, 0, 1, NoneVarRef),
        GetVarRef1 => ("get_var_ref1", 1, 0, 1, NoneVarRef),
        GetVarRef2 => ("get_var_ref2", 1, 0, 1, NoneVarRef),
        GetVarRef3 => ("get_var_ref3", 1, 0, 1, NoneVarRef),
        PutVarRef0 => ("put_var_ref0", 1, 1, 0, NoneVarRef),
        PutVarRef1 => ("put_var_ref1", 1, 1, 0, NoneVarRef),
        PutVarRef2 => ("put_var_ref2", 1, 1, 0, NoneVarRef),
        PutVarRef3 => ("put_var_ref3", 1, 1, 0, NoneVarRef),
        SetVarRef0 => ("set_var_ref0", 1, 1, 1, NoneVarRef),
        SetVarRef1 => ("set_var_ref1", 1, 1, 1, NoneVarRef),
        SetVarRef2 => ("set_var_ref2", 1, 1, 1, NoneVarRef),
        SetVarRef3 => ("set_var_ref3", 1, 1, 1, NoneVarRef),
        GetLength => ("get_length", 1, 1, 1, None),
        IfFalse8 => ("if_false8", 2, 1, 0, Label8),
        IfTrue8 => ("if_true8", 2, 1, 0, Label8),
        Goto8 => ("goto8", 2, 0, 0, Label8),
        Goto16 => ("goto16", 3, 0, 0, Label16),
        Call0 => ("call0", 1, 1, 1, NPopX),
        Call1 => ("call1", 1, 1, 1, NPopX),
        Call2 => ("call2", 1, 1, 1, NPopX),
        Call3 => ("call3", 1, 1, 1, NPopX),
        IsUndefined => ("is_undefined", 1, 1, 1, None),
        IsNull => ("is_null", 1, 1, 1, None),
        TypeofIsUndefined => ("typeof_is_undefined", 1, 1, 1, None),
        TypeofIsFunction => ("typeof_is_function", 1, 1, 1, None),
        // Fusor extension: spread argument lists need their own terminal form
        // so verified proper-tail-call lowering never has to synthesize an
        // unbounded fixed-arity call.
        TailApply => ("tail_apply", 3, 3, 0, U16),
        // The `eval` spellings must preserve the runtime identity check: the
        // intrinsic performs direct eval, while every other callable receives
        // a proper tail transfer.
        TailEval => ("tail_eval", 5, 1, 0, NPopU16),
        TailApplyEval => ("tail_apply_eval", 3, 2, 0, U16),
        // Appended rather than inserted at upstream's `import` adjacency so
        // every pre-existing opcode encoding keeps its byte value.
        ImportMeta => ("import_meta", 1, 0, 1, None),
    }
}
