/*
 * QuickJS bytecode control-flow verification
 *
 * Copyright (c) 2017-2018 Fabrice Bellard
 * Copyright (c) 2017-2018 Charlie Gordon
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

//! Fail-closed verification of final bytecode control flow and ordinary
//! JavaScript-value stack depths.
//!
//! This module intentionally produces [`VerifiedControlFlow`], not an
//! execution-authorizing `VerifiedBytecode`. Atom namespaces, constant kinds,
//! nested functions, handlers, iterator markers, finally return addresses,
//! debug payloads, and source tables still require later verification.

use crate::function::UnverifiedFunctionHeader;

mod error;
mod header;
mod layouts;
mod limits;
mod model;
mod opcode_semantics;
mod operands;
mod predecode;
mod stack;
mod static_control_flow;
mod targets;

pub use error::{
    ControlFlowEdge, FunctionCountDomain, InvalidControlFlowTargetReason, OperandIndexDomain,
    SecondaryOperandField, UnsupportedVerifierFeature, VerificationError, VerificationErrorKind,
};
use header::{validate_function_header, validate_limits_and_counts};
use layouts::{validate_compiler_capture_layout, validate_compiler_constant_layout};
pub use limits::{
    MAX_FUNCTION_INDEX_ENTRIES, MAX_OPERAND_STACK_DEPTH, VerificationLimits, VerificationResource,
};
pub use model::{
    CompilerCaptureLayout, CompilerCapturedBinding, CompilerConstantKind, CompilerConstantLayout,
    FunctionIndexDomains, FunctionPath, InstructionIndex, UnverifiedCompilerFunctionBody,
    UnverifiedFunctionBody, VerifiedControlFlow, VerifiedInstruction, VerifiedSuccessorKind,
    VerifiedSuccessors,
};
use model::{CompilerCapturedBindingIdentity, VerifiedSuccessorsRepr};
use predecode::{PredecodedBody, predecode_complete};
use stack::{StackCertificate, analyze_ordinary_stack};
use static_control_flow::validate_static_semantics;

/// Completely predecodes and verifies the currently supported ordinary-value
/// control-flow subset.
///
/// Predecoding always consumes the complete instruction stream before opcode
/// capability errors are considered. The returned value is not executable
/// bytecode: whole-function metadata and pool validation remain mandatory.
///
/// # Errors
///
/// Returns a contextual [`VerificationError`] for malformed encoding, limits,
/// allocation failure, invalid operands or targets, unsupported semantics,
/// stack underflow, inconsistent joins, or a stored-stack-size mismatch.
pub fn verify_control_flow(
    body: UnverifiedFunctionBody,
    limits: VerificationLimits,
) -> Result<VerifiedControlFlow, VerificationError> {
    let expected_stack_size = body.expected_stack_size;
    let verified = verify_control_flow_common(
        body.bytecode,
        body.domains,
        body.function_header,
        StackVerificationMode::Serialized {
            expected_stack_size,
        },
        None,
        None,
        limits,
    )?;

    if verified.computed_stack_size != expected_stack_size {
        return Err(VerificationError::root(
            VerificationErrorKind::SerializedStackSizeMismatch {
                serialized: expected_stack_size,
                computed: verified.computed_stack_size,
            },
        ));
    }

    Ok(verified)
}

/// Completely predecodes compiler-generated bytecode and derives its exact
/// reachable maximum stack size.
///
/// This uses the same target, opcode, domain, header, reachability, and
/// join-depth checks as [`verify_control_flow`]. Compiler-generated input has
/// no serialized stack-size field to compare, and every reachable terminal
/// must leave the ordinary value stack empty. The returned value remains
/// non-executable staged evidence.
///
/// # Errors
///
/// Returns a contextual [`VerificationError`] for malformed encoding, limits,
/// allocation failure, invalid operands or targets, unsupported semantics,
/// stack underflow, inconsistent joins, or a reachable terminal with residual
/// compiler stack values.
pub fn verify_compiler_control_flow(
    body: UnverifiedCompilerFunctionBody,
    limits: VerificationLimits,
) -> Result<VerifiedControlFlow, VerificationError> {
    let UnverifiedCompilerFunctionBody {
        bytecode,
        domains,
        function_header,
        capture_layout,
        constant_layout,
    } = body;
    verify_control_flow_common(
        bytecode,
        domains,
        function_header,
        StackVerificationMode::CompilerGenerated,
        capture_layout,
        constant_layout,
        limits,
    )
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum StackVerificationMode {
    Serialized { expected_stack_size: u32 },
    CompilerGenerated,
}

impl StackVerificationMode {
    const fn expected_stack_size(self) -> Option<u32> {
        match self {
            Self::Serialized {
                expected_stack_size,
            } => Some(expected_stack_size),
            Self::CompilerGenerated => None,
        }
    }

    const fn requires_empty_exits(self) -> bool {
        matches!(self, Self::CompilerGenerated)
    }
}

fn verify_control_flow_common(
    bytecode: Vec<u8>,
    domains: FunctionIndexDomains,
    function_header: UnverifiedFunctionHeader,
    stack_mode: StackVerificationMode,
    compiler_capture_layout: Option<CompilerCaptureLayout>,
    compiler_constant_layout: Option<CompilerConstantLayout>,
    limits: VerificationLimits,
) -> Result<VerifiedControlFlow, VerificationError> {
    validate_limits_and_counts(
        bytecode.len(),
        domains,
        function_header,
        stack_mode.expected_stack_size(),
        limits,
    )?;

    if bytecode.is_empty() {
        return Err(VerificationError::root(
            VerificationErrorKind::EmptyBytecode,
        ));
    }

    let PredecodedBody {
        instructions: decoded,
        instruction_start_bitmap,
    } = predecode_complete(&bytecode, limits.max_instructions_per_function)?;
    let function_header = validate_function_header(function_header, domains)?;
    if stack_mode.requires_empty_exits()
        && compiler_capture_layout.is_none()
        && function_header.variable_reference_count() != 0
    {
        return Err(VerificationError::root(
            VerificationErrorKind::MissingCompilerCaptureLayout {
                variable_references: function_header.variable_reference_count(),
            },
        ));
    }
    let compiler_capture_layout = compiler_capture_layout
        .map(|layout| validate_compiler_capture_layout(layout, domains, &function_header))
        .transpose()?;
    if stack_mode.requires_empty_exits()
        && compiler_constant_layout.is_none()
        && domains.constant_pool_len != 0
    {
        return Err(VerificationError::root(
            VerificationErrorKind::MissingCompilerConstantLayout {
                constants: domains.constant_pool_len,
            },
        ));
    }
    let compiler_constant_layout = compiler_constant_layout
        .map(|layout| validate_compiler_constant_layout(layout, domains))
        .transpose()?;
    let structurally_verified = validate_static_semantics(
        &decoded,
        &instruction_start_bitmap,
        bytecode.len(),
        domains,
        function_header.kind(),
        compiler_capture_layout.as_ref(),
        compiler_constant_layout.as_ref(),
        stack_mode.requires_empty_exits(),
    )?;
    let StackCertificate {
        instructions,
        computed_stack_size,
        transfer_evaluations,
    } = analyze_ordinary_stack(
        structurally_verified,
        limits,
        stack_mode.requires_empty_exits(),
    )?;

    Ok(VerifiedControlFlow {
        bytecode,
        instructions,
        instruction_start_bitmap,
        computed_stack_size,
        transfer_evaluations,
        domains,
        function_header,
        compiler_capture_layout: compiler_capture_layout.map(|validated| validated.layout),
        compiler_constant_layout,
    })
}

fn usize_to_u64(value: usize) -> u64 {
    u64::try_from(value).unwrap_or(u64::MAX)
}
