/*
 * QuickJS bytecode control-flow verification
 *
 * Copyright (c) 2017-2018 Fabrice Bellard
 * Copyright (c) 2017-2018 Charlie Gordon
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

//! Fail-closed verification of final bytecode control flow and ordinary
//! JavaScript-value stack depths.
//!
//! This module intentionally produces [`VerifiedControlFlow`], not an
//! execution-authorizing `VerifiedBytecode`. Atom namespaces, constant kinds,
//! nested functions, handlers, iterator markers, finally return addresses,
//! debug payloads, and source tables still require later verification.

use std::collections::VecDeque;

use crate::{
    BytecodePc, DecodeError, DecodedInstruction, FinalOpcode, OperandFormat, Operands,
    function::{FunctionKind, FunctionKindRequirement, UnverifiedFunctionHeader},
};

mod error;
mod header;
mod layouts;
mod limits;
mod model;
mod predecode;

pub use error::{
    ControlFlowEdge, FunctionCountDomain, InvalidControlFlowTargetReason, OperandIndexDomain,
    SecondaryOperandField, UnsupportedVerifierFeature, VerificationError, VerificationErrorKind,
};
use header::{validate_function_header, validate_limits_and_counts};
use layouts::{
    ValidatedCompilerCaptureLayout, validate_compiler_capture_layout,
    validate_compiler_constant_layout,
};
pub use limits::{
    MAX_FUNCTION_INDEX_ENTRIES, MAX_OPERAND_STACK_DEPTH, VerificationLimits, VerificationResource,
};
pub use model::{
    CompilerCaptureLayout, CompilerCapturedBinding, CompilerConstantKind, CompilerConstantLayout,
    FunctionIndexDomains, FunctionPath, InstructionIndex, UnverifiedCompilerFunctionBody,
    UnverifiedFunctionBody, VerifiedControlFlow, VerifiedInstruction, VerifiedSuccessorKind,
    VerifiedSuccessors,
};
use model::{CompilerCapturedBindingIdentity, VerifiedSuccessorsRepr};
use predecode::{PredecodedBody, is_instruction_start, predecode_complete};

/// Completely predecodes and verifies the currently supported ordinary-value
/// control-flow subset.
///
/// Predecoding always consumes the complete instruction stream before opcode
/// capability errors are considered. The returned value is not executable
/// bytecode: whole-function metadata and pool validation remain mandatory.
///
/// # Errors
///
/// Returns a contextual [`VerificationError`] for malformed encoding, limits,
/// allocation failure, invalid operands or targets, unsupported semantics,
/// stack underflow, inconsistent joins, or a stored-stack-size mismatch.
pub fn verify_control_flow(
    body: UnverifiedFunctionBody,
    limits: VerificationLimits,
) -> Result<VerifiedControlFlow, VerificationError> {
    let expected_stack_size = body.expected_stack_size;
    let verified = verify_control_flow_common(
        body.bytecode,
        body.domains,
        body.function_header,
        StackVerificationMode::Serialized {
            expected_stack_size,
        },
        None,
        None,
        limits,
    )?;

    if verified.computed_stack_size != expected_stack_size {
        return Err(VerificationError::root(
            VerificationErrorKind::SerializedStackSizeMismatch {
                serialized: expected_stack_size,
                computed: verified.computed_stack_size,
            },
        ));
    }

    Ok(verified)
}

/// Completely predecodes compiler-generated bytecode and derives its exact
/// reachable maximum stack size.
///
/// This uses the same target, opcode, domain, header, reachability, and
/// join-depth checks as [`verify_control_flow`]. Compiler-generated input has
/// no serialized stack-size field to compare, and every reachable terminal
/// must leave the ordinary value stack empty. The returned value remains
/// non-executable staged evidence.
///
/// # Errors
///
/// Returns a contextual [`VerificationError`] for malformed encoding, limits,
/// allocation failure, invalid operands or targets, unsupported semantics,
/// stack underflow, inconsistent joins, or a reachable terminal with residual
/// compiler stack values.
pub fn verify_compiler_control_flow(
    body: UnverifiedCompilerFunctionBody,
    limits: VerificationLimits,
) -> Result<VerifiedControlFlow, VerificationError> {
    let UnverifiedCompilerFunctionBody {
        bytecode,
        domains,
        function_header,
        capture_layout,
        constant_layout,
    } = body;
    verify_control_flow_common(
        bytecode,
        domains,
        function_header,
        StackVerificationMode::CompilerGenerated,
        capture_layout,
        constant_layout,
        limits,
    )
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum StackVerificationMode {
    Serialized { expected_stack_size: u32 },
    CompilerGenerated,
}

impl StackVerificationMode {
    const fn expected_stack_size(self) -> Option<u32> {
        match self {
            Self::Serialized {
                expected_stack_size,
            } => Some(expected_stack_size),
            Self::CompilerGenerated => None,
        }
    }

    const fn requires_empty_exits(self) -> bool {
        matches!(self, Self::CompilerGenerated)
    }
}

fn verify_control_flow_common(
    bytecode: Vec<u8>,
    domains: FunctionIndexDomains,
    function_header: UnverifiedFunctionHeader,
    stack_mode: StackVerificationMode,
    compiler_capture_layout: Option<CompilerCaptureLayout>,
    compiler_constant_layout: Option<CompilerConstantLayout>,
    limits: VerificationLimits,
) -> Result<VerifiedControlFlow, VerificationError> {
    validate_limits_and_counts(
        bytecode.len(),
        domains,
        function_header,
        stack_mode.expected_stack_size(),
        limits,
    )?;

    if bytecode.is_empty() {
        return Err(VerificationError::root(
            VerificationErrorKind::EmptyBytecode,
        ));
    }

    let PredecodedBody {
        instructions: decoded,
        instruction_start_bitmap,
    } = predecode_complete(&bytecode, limits.max_instructions_per_function)?;
    let function_header = validate_function_header(function_header, domains)?;
    if stack_mode.requires_empty_exits()
        && compiler_capture_layout.is_none()
        && function_header.variable_reference_count() != 0
    {
        return Err(VerificationError::root(
            VerificationErrorKind::MissingCompilerCaptureLayout {
                variable_references: function_header.variable_reference_count(),
            },
        ));
    }
    let compiler_capture_layout = compiler_capture_layout
        .map(|layout| validate_compiler_capture_layout(layout, domains, &function_header))
        .transpose()?;
    if stack_mode.requires_empty_exits()
        && compiler_constant_layout.is_none()
        && domains.constant_pool_len != 0
    {
        return Err(VerificationError::root(
            VerificationErrorKind::MissingCompilerConstantLayout {
                constants: domains.constant_pool_len,
            },
        ));
    }
    let compiler_constant_layout = compiler_constant_layout
        .map(|layout| validate_compiler_constant_layout(layout, domains))
        .transpose()?;
    let mut instructions = validate_static_semantics(
        &decoded,
        &instruction_start_bitmap,
        bytecode.len(),
        domains,
        function_header.kind(),
        compiler_capture_layout.as_ref(),
        compiler_constant_layout.as_ref(),
        stack_mode.requires_empty_exits(),
    )?;
    let (computed_stack_size, transfer_evaluations) =
        analyze_ordinary_stack(&mut instructions, limits, stack_mode.requires_empty_exits())?;

    Ok(VerifiedControlFlow {
        bytecode,
        instructions,
        instruction_start_bitmap,
        computed_stack_size,
        transfer_evaluations,
        domains,
        function_header,
        compiler_capture_layout: compiler_capture_layout.map(|validated| validated.layout),
        compiler_constant_layout,
    })
}

#[allow(
    clippy::too_many_arguments,
    reason = "decoded control-flow domains and compiler-only metadata form one static-semantics boundary"
)]
fn validate_static_semantics(
    decoded: &[DecodedInstruction],
    instruction_start_bitmap: &[u64],
    bytecode_len: usize,
    domains: FunctionIndexDomains,
    function_kind: FunctionKind,
    compiler_capture_layout: Option<&ValidatedCompilerCaptureLayout>,
    compiler_constant_layout: Option<&CompilerConstantLayout>,
    compiler_generated: bool,
) -> Result<Vec<VerifiedInstruction>, VerificationError> {
    let mut verified = Vec::new();
    verified.try_reserve_exact(decoded.len()).map_err(|_| {
        VerificationError::root(VerificationErrorKind::AllocationFailed {
            resource: VerificationResource::Instructions,
            requested: usize_to_u64(decoded.len()),
        })
    })?;

    for &current in decoded {
        validate_operand_indices(current, domains)?;
        validate_secondary_operands(current, domains)?;

        let target =
            resolve_relative_target(current, decoded, instruction_start_bitmap, bytecode_len)?;
        validate_gosub_continuation(current, decoded, instruction_start_bitmap, bytecode_len)?;

        let semantics = opcode_semantics(current.instruction().opcode());
        let successors = resolve_static_successors(
            current,
            semantics,
            target,
            decoded,
            instruction_start_bitmap,
            bytecode_len,
        )?;

        verified.push(VerifiedInstruction {
            decoded: current,
            entry_stack_depth: None,
            successors,
        });
    }

    for instruction in &verified {
        let decoded = instruction.decoded;
        if let OpcodeSemantics::Unsupported(feature, _) =
            opcode_semantics(decoded.instruction().opcode())
        {
            if decoded.instruction().opcode() == FinalOpcode::CloseLoc {
                if let Some(capture_layout) = compiler_capture_layout {
                    validate_compiler_close_loc(decoded, capture_layout)?;
                } else {
                    return Err(VerificationError::at_instruction(
                        decoded,
                        VerificationErrorKind::UnsupportedOpcodeSemantics { feature },
                    ));
                }
            } else if matches!(
                decoded.instruction().opcode(),
                FinalOpcode::PushConst
                    | FinalOpcode::FClosure
                    | FinalOpcode::PushConst8
                    | FinalOpcode::FClosure8
            ) {
                if let Some(constant_layout) = compiler_constant_layout {
                    validate_compiler_constant_kind(decoded, constant_layout)?;
                } else {
                    return Err(VerificationError::at_instruction(
                        decoded,
                        VerificationErrorKind::UnsupportedOpcodeSemantics { feature },
                    ));
                }
            } else if compiler_generated
                && matches!(
                    decoded.instruction().opcode(),
                    FinalOpcode::ForOfStart
                        | FinalOpcode::ForOfNext
                        | FinalOpcode::IteratorClose
                        | FinalOpcode::CopyDataProperties
                )
            {
                // Compiler-owned control flow is still non-executable. The
                // whole-function typed stack verifier proves the exact
                // synchronous iterator record before granting authority, and
                // `copy_data_properties`' packed stack offsets keep their
                // net-zero effect (three operand slots popped and re-pushed).
            } else {
                return Err(VerificationError::at_instruction(
                    decoded,
                    VerificationErrorKind::UnsupportedOpcodeSemantics { feature },
                ));
            }
        }
        validate_function_kind_opcode(decoded, function_kind)?;
    }

    Ok(verified)
}

fn validate_compiler_constant_kind(
    decoded: DecodedInstruction,
    constant_layout: &CompilerConstantLayout,
) -> Result<(), VerificationError> {
    let instruction = decoded.instruction();
    let (index, expected) = match (instruction.opcode(), instruction.operands()) {
        (FinalOpcode::PushConst, Operands::Const(index)) => (index, CompilerConstantKind::Value),
        (FinalOpcode::PushConst8, Operands::Const8(index)) => {
            (u32::from(index), CompilerConstantKind::Value)
        }
        (FinalOpcode::FClosure, Operands::Const(index)) => (index, CompilerConstantKind::Function),
        (FinalOpcode::FClosure8, Operands::Const8(index)) => {
            (u32::from(index), CompilerConstantKind::Function)
        }
        _ => {
            return Err(VerificationError::at_instruction(
                decoded,
                VerificationErrorKind::MissingControlFlowOperand {
                    expected: instruction.opcode().metadata().operand_format(),
                },
            ));
        }
    };
    let actual = constant_layout.kind(index).ok_or_else(|| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::IndexOutOfBounds {
                domain: OperandIndexDomain::ConstantPool,
                index,
                len: u32::try_from(constant_layout.kinds.len()).unwrap_or(u32::MAX),
            },
        )
    })?;
    if expected == CompilerConstantKind::Value && actual == CompilerConstantKind::Function {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::UnsupportedOpcodeSemantics {
                feature: UnsupportedVerifierFeature::RawFunctionStack,
            },
        ));
    }
    if actual != expected {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::CompilerConstantKindMismatch {
                index,
                expected,
                actual,
            },
        ));
    }
    Ok(())
}

fn validate_compiler_close_loc(
    decoded: DecodedInstruction,
    capture_layout: &ValidatedCompilerCaptureLayout,
) -> Result<(), VerificationError> {
    let Operands::Loc(local) = decoded.instruction().operands() else {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::MissingControlFlowOperand {
                expected: OperandFormat::Loc,
            },
        ));
    };
    let local = u32::from(local);
    if !capture_layout.is_scoped_local(local) {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::CloseLocRequiresScopedCapture { local },
        ));
    }
    Ok(())
}

fn validate_function_kind_opcode(
    decoded: DecodedInstruction,
    function_kind: FunctionKind,
) -> Result<(), VerificationError> {
    let requirement = match decoded.instruction().opcode() {
        FinalOpcode::TailCall
        | FinalOpcode::TailCallMethod
        | FinalOpcode::Return
        | FinalOpcode::ReturnUndef => FunctionKindRequirement::Normal,
        FinalOpcode::InitialYield | FinalOpcode::Yield => FunctionKindRequirement::Generator,
        FinalOpcode::YieldStar => FunctionKindRequirement::SynchronousGenerator,
        FinalOpcode::AsyncYieldStar => FunctionKindRequirement::AsyncGenerator,
        FinalOpcode::Await => FunctionKindRequirement::Async,
        FinalOpcode::ReturnAsync => FunctionKindRequirement::NonNormal,
        _ => return Ok(()),
    };

    if !requirement.accepts(function_kind) {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::OpcodeNotAllowedForFunctionKind {
                kind: function_kind,
                requirement,
            },
        ));
    }

    Ok(())
}

fn resolve_static_successors(
    current: DecodedInstruction,
    semantics: OpcodeSemantics,
    target: Option<InstructionIndex>,
    instructions: &[DecodedInstruction],
    bitmap: &[u64],
    bytecode_len: usize,
) -> Result<VerifiedSuccessors, VerificationError> {
    let Some(shape) = semantics.successor_shape() else {
        return Err(VerificationError::at_instruction(
            current,
            VerificationErrorKind::Decode(DecodeError::InvalidOpcode {
                pc: current.pc(),
                opcode_byte: FinalOpcode::Invalid.encoded_byte(),
                source: crate::FinalOpcodeDecodeError::ReservedInvalid,
            }),
        ));
    };

    match shape {
        SuccessorShape::Fallthrough => Ok(VerifiedSuccessors(VerifiedSuccessorsRepr::Fallthrough(
            resolve_fallthrough(current, instructions, bitmap, bytecode_len)?,
        ))),
        SuccessorShape::Branch => {
            let taken = require_encoded_target(current, target)?;
            let not_taken = resolve_fallthrough(current, instructions, bitmap, bytecode_len)?;
            Ok(VerifiedSuccessors(VerifiedSuccessorsRepr::Branch {
                taken,
                not_taken,
            }))
        }
        SuccessorShape::Jump => Ok(VerifiedSuccessors(VerifiedSuccessorsRepr::Jump(
            require_encoded_target(current, target)?,
        ))),
        SuccessorShape::Terminate => Ok(VerifiedSuccessors(VerifiedSuccessorsRepr::Terminate)),
    }
}

fn require_encoded_target(
    decoded: DecodedInstruction,
    target: Option<InstructionIndex>,
) -> Result<InstructionIndex, VerificationError> {
    target.ok_or_else(|| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::MissingControlFlowOperand {
                expected: decoded.instruction().opcode().metadata().operand_format(),
            },
        )
    })
}

fn decoded_instruction_index_at(
    instructions: &[DecodedInstruction],
    bitmap: &[u64],
    bytecode_len: usize,
    pc: BytecodePc,
) -> Option<InstructionIndex> {
    if !is_instruction_start(bitmap, bytecode_len, pc) {
        return None;
    }
    let index = instructions
        .binary_search_by_key(&pc, |instruction| instruction.pc())
        .ok()?;
    Some(InstructionIndex(u32::try_from(index).ok()?))
}

fn instruction_index_at(
    instructions: &[VerifiedInstruction],
    bitmap: &[u64],
    bytecode_len: usize,
    pc: BytecodePc,
) -> Option<InstructionIndex> {
    if !is_instruction_start(bitmap, bytecode_len, pc) {
        return None;
    }
    let index = instructions
        .binary_search_by_key(&pc, |instruction| instruction.decoded.pc())
        .ok()?;
    Some(InstructionIndex(u32::try_from(index).ok()?))
}

#[allow(clippy::too_many_lines)]
fn validate_operand_indices(
    decoded: DecodedInstruction,
    domains: FunctionIndexDomains,
) -> Result<(), VerificationError> {
    let instruction = decoded.instruction();
    let operands = instruction.operands();

    if let Some(index) = operands.atom_pool_index() {
        validate_index(
            decoded,
            OperandIndexDomain::AtomPool,
            index.get(),
            domains.atom_pool_len,
        )?;
    }

    match operands {
        Operands::Const(index) => validate_index(
            decoded,
            OperandIndexDomain::ConstantPool,
            index,
            domains.constant_pool_len,
        )?,
        Operands::Const8(index) => validate_index(
            decoded,
            OperandIndexDomain::ConstantPool,
            u32::from(index),
            domains.constant_pool_len,
        )?,
        Operands::Loc(index) => validate_index(
            decoded,
            OperandIndexDomain::Local,
            u32::from(index),
            domains.local_count,
        )?,
        Operands::Loc8(index) => validate_index(
            decoded,
            OperandIndexDomain::Local,
            u32::from(index),
            domains.local_count,
        )?,
        Operands::Arg(index) => validate_index(
            decoded,
            OperandIndexDomain::Argument,
            u32::from(index),
            domains.argument_count,
        )?,
        Operands::VarRef(index) => validate_index(
            decoded,
            OperandIndexDomain::ClosureVariable,
            u32::from(index),
            domains.closure_var_count,
        )?,
        Operands::AtomU16 { value, .. } => match instruction.opcode() {
            FinalOpcode::MakeLocRef => validate_index(
                decoded,
                OperandIndexDomain::Local,
                u32::from(value),
                domains.local_count,
            )?,
            FinalOpcode::MakeArgRef => validate_index(
                decoded,
                OperandIndexDomain::Argument,
                u32::from(value),
                domains.argument_count,
            )?,
            FinalOpcode::MakeVarRefRef => validate_index(
                decoded,
                OperandIndexDomain::ClosureVariable,
                u32::from(value),
                domains.closure_var_count,
            )?,
            _ => {}
        },
        Operands::NoneLoc => {
            let index = implied_local_index(instruction.opcode()).ok_or_else(|| {
                VerificationError::at_instruction(
                    decoded,
                    VerificationErrorKind::MissingControlFlowOperand {
                        expected: OperandFormat::NoneLoc,
                    },
                )
            })?;
            validate_index(
                decoded,
                OperandIndexDomain::Local,
                index,
                domains.local_count,
            )?;
        }
        Operands::NoneArg => {
            let index = implied_argument_index(instruction.opcode()).ok_or_else(|| {
                VerificationError::at_instruction(
                    decoded,
                    VerificationErrorKind::MissingControlFlowOperand {
                        expected: OperandFormat::NoneArg,
                    },
                )
            })?;
            validate_index(
                decoded,
                OperandIndexDomain::Argument,
                index,
                domains.argument_count,
            )?;
        }
        Operands::NoneVarRef => {
            let index = implied_closure_variable_index(instruction.opcode()).ok_or_else(|| {
                VerificationError::at_instruction(
                    decoded,
                    VerificationErrorKind::MissingControlFlowOperand {
                        expected: OperandFormat::NoneVarRef,
                    },
                )
            })?;
            validate_index(
                decoded,
                OperandIndexDomain::ClosureVariable,
                index,
                domains.closure_var_count,
            )?;
        }
        Operands::None
        | Operands::NoneInt
        | Operands::U8(_)
        | Operands::I8(_)
        | Operands::Label8(_)
        | Operands::U16(_)
        | Operands::I16(_)
        | Operands::Label16(_)
        | Operands::NPop { .. }
        | Operands::NPopX
        | Operands::NPopU16 { .. }
        | Operands::U32(_)
        | Operands::I32(_)
        | Operands::Label(_)
        | Operands::Atom(_)
        | Operands::AtomU8 { .. }
        | Operands::AtomLabelU8 { .. }
        | Operands::AtomLabelU16 { .. }
        | Operands::LabelU16 { .. } => {}
    }

    Ok(())
}

fn validate_index(
    decoded: DecodedInstruction,
    domain: OperandIndexDomain,
    index: u32,
    len: u32,
) -> Result<(), VerificationError> {
    if index >= len {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::IndexOutOfBounds { domain, index, len },
        ));
    }
    Ok(())
}

fn implied_local_index(opcode: FinalOpcode) -> Option<u32> {
    match opcode {
        FinalOpcode::GetLoc0 | FinalOpcode::PutLoc0 | FinalOpcode::SetLoc0 => Some(0),
        FinalOpcode::GetLoc1 | FinalOpcode::PutLoc1 | FinalOpcode::SetLoc1 => Some(1),
        FinalOpcode::GetLoc2 | FinalOpcode::PutLoc2 | FinalOpcode::SetLoc2 => Some(2),
        FinalOpcode::GetLoc3 | FinalOpcode::PutLoc3 | FinalOpcode::SetLoc3 => Some(3),
        _ => None,
    }
}

fn implied_argument_index(opcode: FinalOpcode) -> Option<u32> {
    match opcode {
        FinalOpcode::GetArg0 | FinalOpcode::PutArg0 | FinalOpcode::SetArg0 => Some(0),
        FinalOpcode::GetArg1 | FinalOpcode::PutArg1 | FinalOpcode::SetArg1 => Some(1),
        FinalOpcode::GetArg2 | FinalOpcode::PutArg2 | FinalOpcode::SetArg2 => Some(2),
        FinalOpcode::GetArg3 | FinalOpcode::PutArg3 | FinalOpcode::SetArg3 => Some(3),
        _ => None,
    }
}

fn implied_closure_variable_index(opcode: FinalOpcode) -> Option<u32> {
    match opcode {
        FinalOpcode::GetVarRef0 | FinalOpcode::PutVarRef0 | FinalOpcode::SetVarRef0 => Some(0),
        FinalOpcode::GetVarRef1 | FinalOpcode::PutVarRef1 | FinalOpcode::SetVarRef1 => Some(1),
        FinalOpcode::GetVarRef2 | FinalOpcode::PutVarRef2 | FinalOpcode::SetVarRef2 => Some(2),
        FinalOpcode::GetVarRef3 | FinalOpcode::PutVarRef3 | FinalOpcode::SetVarRef3 => Some(3),
        _ => None,
    }
}

fn validate_secondary_operands(
    decoded: DecodedInstruction,
    domains: FunctionIndexDomains,
) -> Result<(), VerificationError> {
    let instruction = decoded.instruction();
    let invalid = |field, value| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::InvalidSecondaryOperand { field, value },
        )
    };

    match (instruction.opcode(), instruction.operands()) {
        (FinalOpcode::SpecialObject, Operands::U8(value)) if value > 6 => Err(invalid(
            SecondaryOperandField::SpecialObjectKind,
            u32::from(value),
        )),
        (FinalOpcode::Rest, Operands::U16(value)) if u32::from(value) > domains.argument_count => {
            Err(invalid(
                SecondaryOperandField::RestFirstArgument,
                u32::from(value),
            ))
        }
        (FinalOpcode::Apply, Operands::U16(value)) if value > 2 => {
            Err(invalid(SecondaryOperandField::ApplyMagic, u32::from(value)))
        }
        (FinalOpcode::ThrowError, Operands::AtomU8 { value, .. }) if value > 4 => Err(invalid(
            SecondaryOperandField::ThrowErrorKind,
            u32::from(value),
        )),
        (FinalOpcode::DefineMethod, Operands::AtomU8 { value, .. })
        | (FinalOpcode::DefineMethodComputed, Operands::U8(value))
            if value & !0b111 != 0 || value & 0b11 == 0b11 =>
        {
            Err(invalid(
                SecondaryOperandField::DefineMethodFlags,
                u32::from(value),
            ))
        }
        (
            FinalOpcode::DefineClass | FinalOpcode::DefineClassComputed,
            Operands::AtomU8 { value, .. },
        ) if value > 1 => Err(invalid(
            SecondaryOperandField::DefineClassFlags,
            u32::from(value),
        )),
        (
            FinalOpcode::WithGetVar
            | FinalOpcode::WithPutVar
            | FinalOpcode::WithDeleteVar
            | FinalOpcode::WithMakeRef
            | FinalOpcode::WithGetRef,
            Operands::AtomLabelU8 { value, .. },
        ) if value > 1 => Err(invalid(SecondaryOperandField::IsWith, u32::from(value))),
        (FinalOpcode::IteratorCall, Operands::U8(value)) if value > 2 => Err(invalid(
            SecondaryOperandField::IteratorCallFlags,
            u32::from(value),
        )),
        _ => Ok(()),
    }
}

fn resolve_relative_target(
    decoded: DecodedInstruction,
    instructions: &[DecodedInstruction],
    bitmap: &[u64],
    bytecode_len: usize,
) -> Result<Option<InstructionIndex>, VerificationError> {
    let Some((edge, base_delta, displacement)) = relative_target_spec(decoded)? else {
        return Ok(None);
    };
    let pc = i64::from(decoded.pc().get());
    let base = pc.checked_add(base_delta).ok_or_else(|| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::ControlFlowTargetOverflow {
                edge,
                base: pc,
                displacement: base_delta,
            },
        )
    })?;
    let target = base.checked_add(displacement).ok_or_else(|| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::ControlFlowTargetOverflow {
                edge,
                base,
                displacement,
            },
        )
    })?;
    resolve_target(decoded, edge, target, instructions, bitmap, bytecode_len).map(Some)
}

fn relative_target_spec(
    decoded: DecodedInstruction,
) -> Result<Option<(ControlFlowEdge, i64, i64)>, VerificationError> {
    let instruction = decoded.instruction();
    let opcode = instruction.opcode();
    let operands = instruction.operands();

    let missing = |expected| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::MissingControlFlowOperand { expected },
        )
    };

    match opcode {
        FinalOpcode::IfFalse8 | FinalOpcode::IfTrue8 => match operands {
            Operands::Label8(displacement) => {
                Ok(Some((ControlFlowEdge::Branch, 1, i64::from(displacement))))
            }
            _ => Err(missing(OperandFormat::Label8)),
        },
        FinalOpcode::IfFalse | FinalOpcode::IfTrue => match operands {
            Operands::Label(displacement) => {
                Ok(Some((ControlFlowEdge::Branch, 1, i64::from(displacement))))
            }
            _ => Err(missing(OperandFormat::Label)),
        },
        FinalOpcode::Goto8 => match operands {
            Operands::Label8(displacement) => {
                Ok(Some((ControlFlowEdge::Jump, 1, i64::from(displacement))))
            }
            _ => Err(missing(OperandFormat::Label8)),
        },
        FinalOpcode::Goto16 => match operands {
            Operands::Label16(displacement) => {
                Ok(Some((ControlFlowEdge::Jump, 1, i64::from(displacement))))
            }
            _ => Err(missing(OperandFormat::Label16)),
        },
        FinalOpcode::Goto => match operands {
            Operands::Label(displacement) => {
                Ok(Some((ControlFlowEdge::Jump, 1, i64::from(displacement))))
            }
            _ => Err(missing(OperandFormat::Label)),
        },
        FinalOpcode::Catch => match operands {
            Operands::Label(displacement) => Ok(Some((
                ControlFlowEdge::CatchHandler,
                1,
                i64::from(displacement),
            ))),
            _ => Err(missing(OperandFormat::Label)),
        },
        FinalOpcode::Gosub => match operands {
            Operands::Label(displacement) => Ok(Some((
                ControlFlowEdge::FinallySubroutine,
                1,
                i64::from(displacement),
            ))),
            _ => Err(missing(OperandFormat::Label)),
        },
        FinalOpcode::WithGetVar
        | FinalOpcode::WithPutVar
        | FinalOpcode::WithDeleteVar
        | FinalOpcode::WithMakeRef
        | FinalOpcode::WithGetRef => match operands {
            Operands::AtomLabelU8 { label, .. } => {
                Ok(Some((ControlFlowEdge::WithBinding, 5, i64::from(label))))
            }
            _ => Err(missing(OperandFormat::AtomLabelU8)),
        },
        _ => Ok(None),
    }
}

fn validate_gosub_continuation(
    decoded: DecodedInstruction,
    instructions: &[DecodedInstruction],
    bitmap: &[u64],
    bytecode_len: usize,
) -> Result<(), VerificationError> {
    if decoded.instruction().opcode() != FinalOpcode::Gosub {
        return Ok(());
    }
    resolve_target(
        decoded,
        ControlFlowEdge::FinallyContinuation,
        i64::from(decoded.next_pc().get()),
        instructions,
        bitmap,
        bytecode_len,
    )?;
    Ok(())
}

fn resolve_fallthrough(
    decoded: DecodedInstruction,
    instructions: &[DecodedInstruction],
    bitmap: &[u64],
    bytecode_len: usize,
) -> Result<InstructionIndex, VerificationError> {
    resolve_target(
        decoded,
        ControlFlowEdge::Fallthrough,
        i64::from(decoded.next_pc().get()),
        instructions,
        bitmap,
        bytecode_len,
    )
}

fn resolve_target(
    decoded: DecodedInstruction,
    edge: ControlFlowEdge,
    target: i64,
    instructions: &[DecodedInstruction],
    bitmap: &[u64],
    bytecode_len: usize,
) -> Result<InstructionIndex, VerificationError> {
    let bytecode_len_u32 = u32::try_from(bytecode_len).map_err(|_| {
        VerificationError::root(VerificationErrorKind::LimitExceeded {
            resource: VerificationResource::BytecodeBytes,
            limit: u64::from(u32::MAX),
            observed: usize_to_u64(bytecode_len),
        })
    })?;

    if target < 0 || target >= i64::from(bytecode_len_u32) {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::InvalidControlFlowTarget {
                edge,
                target,
                bytecode_len: bytecode_len_u32,
                reason: InvalidControlFlowTargetReason::OutsideBytecode,
            },
        ));
    }
    if decoded.instruction().opcode() == FinalOpcode::Catch && target == 0 {
        return Err(VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::InvalidControlFlowTarget {
                edge,
                target,
                bytecode_len: bytecode_len_u32,
                reason: InvalidControlFlowTargetReason::CatchTargetZero,
            },
        ));
    }

    let target_pc = BytecodePc::new(u32::try_from(target).map_err(|_| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::InvalidControlFlowTarget {
                edge,
                target,
                bytecode_len: bytecode_len_u32,
                reason: InvalidControlFlowTargetReason::OutsideBytecode,
            },
        )
    })?);
    decoded_instruction_index_at(instructions, bitmap, bytecode_len, target_pc).ok_or_else(|| {
        VerificationError::at_instruction(
            decoded,
            VerificationErrorKind::InvalidControlFlowTarget {
                edge,
                target,
                bytecode_len: bytecode_len_u32,
                reason: InvalidControlFlowTargetReason::NotInstructionBoundary,
            },
        )
    })
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum OpcodeSemantics {
    Invalid,
    Ordinary,
    Conditional,
    Jump,
    Terminate,
    Unsupported(UnsupportedVerifierFeature, SuccessorShape),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum SuccessorShape {
    Fallthrough,
    Branch,
    Jump,
    Terminate,
}

impl OpcodeSemantics {
    const fn successor_shape(self) -> Option<SuccessorShape> {
        match self {
            Self::Invalid => None,
            Self::Ordinary => Some(SuccessorShape::Fallthrough),
            Self::Conditional => Some(SuccessorShape::Branch),
            Self::Jump => Some(SuccessorShape::Jump),
            Self::Terminate => Some(SuccessorShape::Terminate),
            Self::Unsupported(_, shape) => Some(shape),
        }
    }
}

#[allow(clippy::too_many_lines)]
const fn opcode_semantics(opcode: FinalOpcode) -> OpcodeSemantics {
    match opcode {
        FinalOpcode::Invalid => OpcodeSemantics::Invalid,

        FinalOpcode::IfFalse
        | FinalOpcode::IfTrue
        | FinalOpcode::IfFalse8
        | FinalOpcode::IfTrue8
        | FinalOpcode::Catch
        | FinalOpcode::Gosub => OpcodeSemantics::Conditional,

        FinalOpcode::Goto | FinalOpcode::Goto8 | FinalOpcode::Goto16 => OpcodeSemantics::Jump,

        FinalOpcode::TailCall
        | FinalOpcode::TailCallMethod
        | FinalOpcode::Return
        | FinalOpcode::ReturnUndef
        | FinalOpcode::ReturnAsync
        | FinalOpcode::Throw
        | FinalOpcode::ThrowError
        | FinalOpcode::Ret => OpcodeSemantics::Terminate,

        FinalOpcode::PushConst
        | FinalOpcode::FClosure
        | FinalOpcode::PushConst8
        | FinalOpcode::FClosure8 => OpcodeSemantics::Unsupported(
            UnsupportedVerifierFeature::ConstantPoolTyping,
            SuccessorShape::Fallthrough,
        ),

        FinalOpcode::DefineClass | FinalOpcode::DefineClassComputed => {
            OpcodeSemantics::Unsupported(
                UnsupportedVerifierFeature::RawFunctionStack,
                SuccessorShape::Fallthrough,
            )
        }

        FinalOpcode::Eval | FinalOpcode::ApplyEval => OpcodeSemantics::Unsupported(
            UnsupportedVerifierFeature::EvalScopeMetadata,
            SuccessorShape::Fallthrough,
        ),

        FinalOpcode::CloseLoc
        | FinalOpcode::MakeLocRef
        | FinalOpcode::MakeArgRef
        | FinalOpcode::MakeVarRefRef
        | FinalOpcode::MakeVarRef => OpcodeSemantics::Unsupported(
            UnsupportedVerifierFeature::CapturedBindingMetadata,
            SuccessorShape::Fallthrough,
        ),

        FinalOpcode::WithGetVar
        | FinalOpcode::WithPutVar
        | FinalOpcode::WithDeleteVar
        | FinalOpcode::WithMakeRef
        | FinalOpcode::WithGetRef => OpcodeSemantics::Unsupported(
            UnsupportedVerifierFeature::WithEnvironmentBranches,
            SuccessorShape::Branch,
        ),

        FinalOpcode::ForOfStart
        | FinalOpcode::ForAwaitOfStart
        | FinalOpcode::ForOfNext
        | FinalOpcode::ForAwaitOfNext
        | FinalOpcode::IteratorGetValueDone
        | FinalOpcode::IteratorClose
        | FinalOpcode::IteratorNext
        | FinalOpcode::IteratorCall => OpcodeSemantics::Unsupported(
            UnsupportedVerifierFeature::IteratorMarkers,
            SuccessorShape::Fallthrough,
        ),

        FinalOpcode::CopyDataProperties => OpcodeSemantics::Unsupported(
            UnsupportedVerifierFeature::PackedStackOffsets,
            SuccessorShape::Fallthrough,
        ),

        FinalOpcode::NipCatch
        | FinalOpcode::PushI32
        | FinalOpcode::InitialYield
        | FinalOpcode::Yield
        | FinalOpcode::YieldStar
        | FinalOpcode::AsyncYieldStar
        | FinalOpcode::Await
        | FinalOpcode::PushAtomValue
        | FinalOpcode::PrivateSymbol
        | FinalOpcode::Undefined
        | FinalOpcode::Null
        | FinalOpcode::PushThis
        | FinalOpcode::PushFalse
        | FinalOpcode::PushTrue
        | FinalOpcode::Object
        | FinalOpcode::SpecialObject
        | FinalOpcode::Rest
        | FinalOpcode::Drop
        | FinalOpcode::Nip
        | FinalOpcode::Nip1
        | FinalOpcode::Dup
        | FinalOpcode::Dup1
        | FinalOpcode::Dup2
        | FinalOpcode::Dup3
        | FinalOpcode::Insert2
        | FinalOpcode::Insert3
        | FinalOpcode::Insert4
        | FinalOpcode::Perm3
        | FinalOpcode::Perm4
        | FinalOpcode::Perm5
        | FinalOpcode::Swap
        | FinalOpcode::Swap2
        | FinalOpcode::Rot3l
        | FinalOpcode::Rot3r
        | FinalOpcode::Rot4l
        | FinalOpcode::Rot5l
        | FinalOpcode::CallConstructor
        | FinalOpcode::Call
        | FinalOpcode::CallMethod
        | FinalOpcode::ArrayFrom
        | FinalOpcode::Apply
        | FinalOpcode::CheckCtorReturn
        | FinalOpcode::CheckCtor
        | FinalOpcode::InitCtor
        | FinalOpcode::CheckBrand
        | FinalOpcode::AddBrand
        | FinalOpcode::RegExp
        | FinalOpcode::GetSuper
        | FinalOpcode::Import
        | FinalOpcode::GetVarUndef
        | FinalOpcode::GetVar
        | FinalOpcode::PutVar
        | FinalOpcode::PutVarInit
        | FinalOpcode::GetRefValue
        | FinalOpcode::PutRefValue
        | FinalOpcode::GetField
        | FinalOpcode::GetField2
        | FinalOpcode::PutField
        | FinalOpcode::GetPrivateField
        | FinalOpcode::PutPrivateField
        | FinalOpcode::DefinePrivateField
        | FinalOpcode::GetArrayEl
        | FinalOpcode::GetArrayEl2
        | FinalOpcode::GetArrayEl3
        | FinalOpcode::PutArrayEl
        | FinalOpcode::GetSuperValue
        | FinalOpcode::PutSuperValue
        | FinalOpcode::DefineField
        | FinalOpcode::SetName
        | FinalOpcode::SetNameComputed
        | FinalOpcode::SetProto
        | FinalOpcode::SetHomeObject
        | FinalOpcode::DefineArrayEl
        | FinalOpcode::Append
        | FinalOpcode::DefineMethod
        | FinalOpcode::DefineMethodComputed
        | FinalOpcode::GetLoc
        | FinalOpcode::PutLoc
        | FinalOpcode::SetLoc
        | FinalOpcode::GetArg
        | FinalOpcode::PutArg
        | FinalOpcode::SetArg
        | FinalOpcode::GetVarRef
        | FinalOpcode::PutVarRef
        | FinalOpcode::SetVarRef
        | FinalOpcode::SetLocUninitialized
        | FinalOpcode::GetLocCheck
        | FinalOpcode::PutLocCheck
        | FinalOpcode::SetLocCheck
        | FinalOpcode::PutLocCheckInit
        | FinalOpcode::GetLocCheckThis
        | FinalOpcode::GetVarRefCheck
        | FinalOpcode::PutVarRefCheck
        | FinalOpcode::PutVarRefCheckInit
        | FinalOpcode::ToObject
        | FinalOpcode::ToPropKey
        | FinalOpcode::ForInStart
        | FinalOpcode::ForInNext
        | FinalOpcode::IteratorCheckObject
        | FinalOpcode::Neg
        | FinalOpcode::Plus
        | FinalOpcode::Dec
        | FinalOpcode::Inc
        | FinalOpcode::PostDec
        | FinalOpcode::PostInc
        | FinalOpcode::DecLoc
        | FinalOpcode::IncLoc
        | FinalOpcode::AddLoc
        | FinalOpcode::Not
        | FinalOpcode::Lnot
        | FinalOpcode::Typeof
        | FinalOpcode::Delete
        | FinalOpcode::DeleteVar
        | FinalOpcode::Mul
        | FinalOpcode::Div
        | FinalOpcode::Mod
        | FinalOpcode::Add
        | FinalOpcode::Sub
        | FinalOpcode::Pow
        | FinalOpcode::Shl
        | FinalOpcode::Sar
        | FinalOpcode::Shr
        | FinalOpcode::Lt
        | FinalOpcode::Lte
        | FinalOpcode::Gt
        | FinalOpcode::Gte
        | FinalOpcode::InstanceOf
        | FinalOpcode::In
        | FinalOpcode::Eq
        | FinalOpcode::Neq
        | FinalOpcode::StrictEq
        | FinalOpcode::StrictNeq
        | FinalOpcode::And
        | FinalOpcode::Xor
        | FinalOpcode::Or
        | FinalOpcode::IsUndefinedOrNull
        | FinalOpcode::PrivateIn
        | FinalOpcode::PushBigIntI32
        | FinalOpcode::Nop
        | FinalOpcode::PushMinus1
        | FinalOpcode::Push0
        | FinalOpcode::Push1
        | FinalOpcode::Push2
        | FinalOpcode::Push3
        | FinalOpcode::Push4
        | FinalOpcode::Push5
        | FinalOpcode::Push6
        | FinalOpcode::Push7
        | FinalOpcode::PushI8
        | FinalOpcode::PushI16
        | FinalOpcode::PushEmptyString
        | FinalOpcode::GetLoc8
        | FinalOpcode::PutLoc8
        | FinalOpcode::SetLoc8
        | FinalOpcode::GetLoc0
        | FinalOpcode::GetLoc1
        | FinalOpcode::GetLoc2
        | FinalOpcode::GetLoc3
        | FinalOpcode::PutLoc0
        | FinalOpcode::PutLoc1
        | FinalOpcode::PutLoc2
        | FinalOpcode::PutLoc3
        | FinalOpcode::SetLoc0
        | FinalOpcode::SetLoc1
        | FinalOpcode::SetLoc2
        | FinalOpcode::SetLoc3
        | FinalOpcode::GetArg0
        | FinalOpcode::GetArg1
        | FinalOpcode::GetArg2
        | FinalOpcode::GetArg3
        | FinalOpcode::PutArg0
        | FinalOpcode::PutArg1
        | FinalOpcode::PutArg2
        | FinalOpcode::PutArg3
        | FinalOpcode::SetArg0
        | FinalOpcode::SetArg1
        | FinalOpcode::SetArg2
        | FinalOpcode::SetArg3
        | FinalOpcode::GetVarRef0
        | FinalOpcode::GetVarRef1
        | FinalOpcode::GetVarRef2
        | FinalOpcode::GetVarRef3
        | FinalOpcode::PutVarRef0
        | FinalOpcode::PutVarRef1
        | FinalOpcode::PutVarRef2
        | FinalOpcode::PutVarRef3
        | FinalOpcode::SetVarRef0
        | FinalOpcode::SetVarRef1
        | FinalOpcode::SetVarRef2
        | FinalOpcode::SetVarRef3
        | FinalOpcode::GetLength
        | FinalOpcode::Call0
        | FinalOpcode::Call1
        | FinalOpcode::Call2
        | FinalOpcode::Call3
        | FinalOpcode::IsUndefined
        | FinalOpcode::IsNull
        | FinalOpcode::TypeofIsUndefined
        | FinalOpcode::TypeofIsFunction => OpcodeSemantics::Ordinary,
    }
}

#[allow(clippy::too_many_lines)]
fn analyze_ordinary_stack(
    instructions: &mut [VerifiedInstruction],
    limits: VerificationLimits,
    require_empty_exits: bool,
) -> Result<(u32, u64), VerificationError> {
    let Some(entry) = instructions.first_mut() else {
        return Err(VerificationError::root(
            VerificationErrorKind::EmptyBytecode,
        ));
    };
    entry.entry_stack_depth = Some(0);

    let mut worklist = VecDeque::new();
    reserve_worklist_entry(&mut worklist, entry.decoded)?;
    worklist.push_back(InstructionIndex(0));

    let mut computed_max = 0_u32;
    let mut evaluations = 0_u64;
    let has_catch_marker = instructions.iter().any(|instruction| {
        matches!(
            instruction.decoded.instruction().opcode(),
            FinalOpcode::Catch | FinalOpcode::ForOfStart
        )
    });
    let has_gosub = instructions
        .iter()
        .any(|instruction| instruction.decoded.instruction().opcode() == FinalOpcode::Gosub);

    while let Some(index) = worklist.pop_front() {
        let position = usize::try_from(index.get()).map_err(|_| {
            VerificationError::root(VerificationErrorKind::LimitExceeded {
                resource: VerificationResource::Instructions,
                limit: u64::from(u32::MAX),
                observed: u64::from(index.get()),
            })
        })?;
        let Some(current) = instructions.get(position).copied() else {
            return Err(VerificationError::root(
                VerificationErrorKind::LimitExceeded {
                    resource: VerificationResource::Instructions,
                    limit: usize_to_u64(instructions.len()),
                    observed: u64::from(index.get()) + 1,
                },
            ));
        };
        let Some(entry_depth) = current.entry_stack_depth else {
            continue;
        };

        evaluations = evaluations.checked_add(1).ok_or_else(|| {
            VerificationError::at_instruction(
                current.decoded,
                VerificationErrorKind::LimitExceeded {
                    resource: VerificationResource::TransferEvaluations,
                    limit: limits.max_transfer_evaluations,
                    observed: u64::MAX,
                },
            )
        })?;
        if evaluations > limits.max_transfer_evaluations {
            return Err(VerificationError::at_instruction(
                current.decoded,
                VerificationErrorKind::LimitExceeded {
                    resource: VerificationResource::TransferEvaluations,
                    limit: limits.max_transfer_evaluations,
                    observed: evaluations,
                },
            ));
        }

        let effect = current
            .decoded
            .instruction()
            .stack_effect()
            .map_err(|source| {
                VerificationError::at_instruction(
                    current.decoded,
                    VerificationErrorKind::StackEffect(source),
                )
            })?;
        if entry_depth < effect.pops() {
            return Err(VerificationError::at_instruction(
                current.decoded,
                VerificationErrorKind::StackUnderflow {
                    required: effect.pops(),
                    available: entry_depth,
                },
            ));
        }
        let output_depth = u64::from(entry_depth - effect.pops()) + u64::from(effect.pushes());
        if output_depth > u64::from(limits.max_stack_depth) {
            return Err(VerificationError::at_instruction(
                current.decoded,
                VerificationErrorKind::StackLimitExceeded {
                    depth: output_depth,
                    limit: limits.max_stack_depth,
                },
            ));
        }
        let output_depth = u32::try_from(output_depth).map_err(|_| {
            VerificationError::at_instruction(
                current.decoded,
                VerificationErrorKind::StackLimitExceeded {
                    depth: output_depth,
                    limit: limits.max_stack_depth,
                },
            )
        })?;
        computed_max = computed_max.max(output_depth);
        let finally_subroutine_depth =
            if current.decoded.instruction().opcode() == FinalOpcode::Gosub {
                let depth = u64::from(output_depth).checked_add(1).ok_or_else(|| {
                    VerificationError::at_instruction(
                        current.decoded,
                        VerificationErrorKind::StackLimitExceeded {
                            depth: u64::MAX,
                            limit: limits.max_stack_depth,
                        },
                    )
                })?;
                if depth > u64::from(limits.max_stack_depth) {
                    return Err(VerificationError::at_instruction(
                        current.decoded,
                        VerificationErrorKind::StackLimitExceeded {
                            depth,
                            limit: limits.max_stack_depth,
                        },
                    ));
                }
                let depth = u32::try_from(depth).map_err(|_| {
                    VerificationError::at_instruction(
                        current.decoded,
                        VerificationErrorKind::StackLimitExceeded {
                            depth,
                            limit: limits.max_stack_depth,
                        },
                    )
                })?;
                computed_max = computed_max.max(depth);
                Some(depth)
            } else {
                None
            };

        match current.successors.0 {
            VerifiedSuccessorsRepr::Fallthrough(successor)
            | VerifiedSuccessorsRepr::Jump(successor) => propagate_stack_depth(
                instructions,
                &mut worklist,
                successor,
                output_depth,
                current.decoded,
            )?,
            VerifiedSuccessorsRepr::Branch { taken, not_taken } => {
                propagate_stack_depth(
                    instructions,
                    &mut worklist,
                    taken,
                    finally_subroutine_depth.unwrap_or(output_depth),
                    current.decoded,
                )?;
                propagate_stack_depth(
                    instructions,
                    &mut worklist,
                    not_taken,
                    output_depth,
                    current.decoded,
                )?;
            }
            VerifiedSuccessorsRepr::Terminate => {
                let protected_throw = has_catch_marker
                    && current.decoded.instruction().opcode() == FinalOpcode::Throw;
                let returns_from_finally =
                    current.decoded.instruction().opcode() == FinalOpcode::Ret;
                // This structural pass cannot distinguish the pending
                // completion and return-address slots introduced by `gosub`.
                // A body containing `gosub` may therefore defer non-empty
                // abrupt-exit proof to the whole-bytecode typed stack pass.
                // `VerifiedControlFlow` alone remains non-executable.
                let defers_typed_finally_exit = has_gosub
                    && matches!(
                        current.decoded.instruction().opcode(),
                        FinalOpcode::Return | FinalOpcode::ReturnUndef | FinalOpcode::Throw
                    );
                if require_empty_exits
                    && output_depth != 0
                    && !protected_throw
                    && !returns_from_finally
                    && !defers_typed_finally_exit
                {
                    return Err(VerificationError::at_instruction(
                        current.decoded,
                        VerificationErrorKind::NonEmptyCompilerExitStack {
                            remaining: output_depth,
                        },
                    ));
                }
            }
        }
    }

    Ok((computed_max, evaluations))
}

fn propagate_stack_depth(
    instructions: &mut [VerifiedInstruction],
    worklist: &mut VecDeque<InstructionIndex>,
    target: InstructionIndex,
    incoming_depth: u32,
    source: DecodedInstruction,
) -> Result<(), VerificationError> {
    let position = usize::try_from(target.get()).map_err(|_| {
        VerificationError::at_instruction(
            source,
            VerificationErrorKind::LimitExceeded {
                resource: VerificationResource::Instructions,
                limit: u64::from(u32::MAX),
                observed: u64::from(target.get()),
            },
        )
    })?;
    let Some(target_instruction) = instructions.get_mut(position) else {
        return Err(VerificationError::at_instruction(
            source,
            VerificationErrorKind::LimitExceeded {
                resource: VerificationResource::Instructions,
                limit: usize_to_u64(instructions.len()),
                observed: u64::from(target.get()) + 1,
            },
        ));
    };

    match target_instruction.entry_stack_depth {
        None => {
            reserve_worklist_entry(worklist, source)?;
            target_instruction.entry_stack_depth = Some(incoming_depth);
            worklist.push_back(target);
        }
        Some(established_depth) if established_depth == incoming_depth => {}
        Some(established_depth) => {
            return Err(VerificationError::at_instruction(
                source,
                VerificationErrorKind::InconsistentStackAtJoin {
                    target: target_instruction.decoded.pc(),
                    established_depth,
                    incoming_depth,
                    incoming_from: source.pc(),
                },
            ));
        }
    }
    Ok(())
}

fn reserve_worklist_entry(
    worklist: &mut VecDeque<InstructionIndex>,
    decoded: DecodedInstruction,
) -> Result<(), VerificationError> {
    if worklist.len() == worklist.capacity() {
        worklist.try_reserve(1).map_err(|_| {
            VerificationError::at_instruction(
                decoded,
                VerificationErrorKind::AllocationFailed {
                    resource: VerificationResource::WorklistEntries,
                    requested: 1,
                },
            )
        })?;
    }
    Ok(())
}

fn usize_to_u64(value: usize) -> u64 {
    u64::try_from(value).unwrap_or(u64::MAX)
}

#[cfg(test)]
mod tests {
    use super::{OpcodeSemantics, opcode_semantics};
    use crate::{ALL_FINAL_OPCODES, FinalOpcode};

    #[test]
    fn final_opcode_capability_partition_is_exhaustive_and_counted_from_the_table() {
        let mut invalid = 0;
        let mut supported = 0;
        let mut unsupported = 0;

        for &opcode in ALL_FINAL_OPCODES {
            match opcode_semantics(opcode) {
                OpcodeSemantics::Invalid => invalid += 1,
                OpcodeSemantics::Unsupported(_, _) => unsupported += 1,
                OpcodeSemantics::Ordinary
                | OpcodeSemantics::Conditional
                | OpcodeSemantics::Jump
                | OpcodeSemantics::Terminate => supported += 1,
            }
        }

        assert_eq!(invalid, 1);
        assert_eq!(supported, 216);
        assert_eq!(unsupported, 27);
        assert_eq!(invalid + supported + unsupported, ALL_FINAL_OPCODES.len());
        assert_eq!(
            opcode_semantics(FinalOpcode::Invalid),
            OpcodeSemantics::Invalid
        );
    }
}
