//! ES Unicode properties of strings not already exposed as a dynamic ICU4X set.
//!
//! The flag-range encoding is the MIT-licensed representation generated by
//! `QuickJS` 2026-06-04. Its decoder is a safe Rust port of `unicode_prop1`.

use icu::properties::{
    CodePointSetData, EmojiSetData,
    props::{BasicEmoji, EmojiModifierBase},
};

const RGI_FLAG_SEQUENCE: [u8; 128] = [
    0x0c, 0x00, 0x09, 0x00, 0x04, 0x01, 0x02, 0x06, 0x03, 0x03, 0x01, 0x02, 0x01, 0x03, 0x07, 0x0d,
    0x18, 0x00, 0x09, 0x00, 0x00, 0x89, 0x08, 0x00, 0x00, 0x81, 0x88, 0x83, 0x8c, 0x10, 0x00, 0x01,
    0x07, 0x08, 0x29, 0x10, 0x28, 0x00, 0x80, 0x8a, 0x00, 0x0a, 0x00, 0x0e, 0x15, 0x18, 0x83, 0x89,
    0x06, 0x00, 0x81, 0x8d, 0x00, 0x12, 0x08, 0x00, 0x03, 0x00, 0x24, 0x00, 0x05, 0x21, 0x00, 0x00,
    0x29, 0x90, 0x00, 0x02, 0x00, 0x08, 0x09, 0x00, 0x08, 0x18, 0x8b, 0x80, 0x8c, 0x02, 0x19, 0x1a,
    0x11, 0x00, 0x00, 0x80, 0x9c, 0x80, 0x88, 0x02, 0x00, 0x00, 0x02, 0x20, 0x88, 0x0a, 0x00, 0x03,
    0x01, 0x02, 0x05, 0x08, 0x00, 0x01, 0x09, 0x20, 0x21, 0x18, 0x22, 0x00, 0x00, 0x00, 0x00, 0x18,
    0x28, 0x89, 0x80, 0x8b, 0x80, 0x90, 0x80, 0x92, 0x80, 0x8d, 0x05, 0x80, 0x8a, 0x80, 0x88, 0x80,
];

pub(crate) fn supports(name: &str) -> bool {
    matches!(
        name,
        "Basic_Emoji"
            | "Emoji_Keycap_Sequence"
            | "RGI_Emoji_Modifier_Sequence"
            | "RGI_Emoji_Flag_Sequence"
            | "RGI_Emoji_Tag_Sequence"
    )
}

pub(crate) fn matches(name: &str, sequence: &[u32]) -> bool {
    match name {
        "Basic_Emoji" => to_string(sequence)
            .is_some_and(|value| EmojiSetData::new::<BasicEmoji>().contains_str(&value)),
        "Emoji_Keycap_Sequence" => {
            matches!(sequence, [first, 0xfe0f, 0x20e3]
                if matches!(*first, 0x23 | 0x2a | 0x30..=0x39))
        }
        "RGI_Emoji_Modifier_Sequence" => matches!(sequence, [base, 0x1f3fb..=0x1f3ff]
            if CodePointSetData::new::<EmojiModifierBase>().contains32(*base)),
        "RGI_Emoji_Flag_Sequence" => matches!(sequence, [first, second]
            if is_valid_flag(*first, *second)),
        "RGI_Emoji_Tag_Sequence" => is_valid_tag_sequence(sequence),
        _ => false,
    }
}

fn to_string(sequence: &[u32]) -> Option<String> {
    sequence.iter().copied().map(char::from_u32).collect()
}

fn is_valid_flag(first: u32, second: u32) -> bool {
    if !(0x1f1e6..=0x1f1ff).contains(&first) || !(0x1f1e6..=0x1f1ff).contains(&second) {
        return false;
    }
    let index = (first - 0x1f1e6) * 26 + second - 0x1f1e6;
    compressed_property_contains(&RGI_FLAG_SEQUENCE, index)
}

fn is_valid_tag_sequence(sequence: &[u32]) -> bool {
    let Some((&0x1f3f4, tagged)) = sequence.split_first() else {
        return false;
    };
    let Some((&0xe007f, tags)) = tagged.split_last() else {
        return false;
    };
    let mut name = String::with_capacity(tags.len());
    for &tag in tags {
        let Some(ascii) = tag.checked_sub(0xe0000).and_then(char::from_u32) else {
            return false;
        };
        name.push(ascii);
    }
    matches!(name.as_str(), "gbeng" | "gbsct" | "gbwls")
}

fn compressed_property_contains(table: &[u8], value: u32) -> bool {
    let mut cursor = 0;
    let mut code_point = 0_u32;
    let mut included = false;
    while cursor < table.len() {
        let start = code_point;
        let byte = table[cursor];
        cursor += 1;
        if byte < 0x40 {
            code_point += u32::from(byte >> 3) + 1;
            if included && (start..code_point).contains(&value) {
                return true;
            }
            included = !included;
            let start = code_point;
            code_point += u32::from(byte & 7) + 1;
            if included && (start..code_point).contains(&value) {
                return true;
            }
        } else if byte >= 0x80 {
            code_point += u32::from(byte - 0x80) + 1;
            if included && (start..code_point).contains(&value) {
                return true;
            }
        } else if byte < 0x60 {
            let Some(&next) = table.get(cursor) else {
                return false;
            };
            cursor += 1;
            code_point += (u32::from(byte - 0x40) << 8 | u32::from(next)) + 1;
            if included && (start..code_point).contains(&value) {
                return true;
            }
        } else {
            let Some((&high, rest)) = table.get(cursor).zip(table.get(cursor + 1)) else {
                return false;
            };
            cursor += 2;
            code_point +=
                (u32::from(byte - 0x60) << 16 | u32::from(high) << 8 | u32::from(*rest)) + 1;
            if included && (start..code_point).contains(&value) {
                return true;
            }
        }
        included = !included;
        if code_point > value && !included {
            return false;
        }
    }
    false
}
