//! The pinned `QuickJS` parser diagnostic ledger.
//!
//! Every `SyntaxError` the pinned `QuickJS` 2026-06-04 front end can raise
//! while compiling a source text appears here exactly once, together with the
//! `quickjs.c` call sites that raise it and whether the corpus can provoke it.
//! The table is the parser ledger's closed early-error vocabulary: a fixture
//! may only declare a diagnostic listed here, every `Reachable` diagnostic must
//! have a fixture, and no `Unreachable` diagnostic may have one.
//!
//! `message` keeps the pinned format string. `%c`, `%s`, and `%.*s` are runtime
//! substitutions, so the oracle comparison treats them as wildcards while every
//! literal character must still match.
//!
//! # Scope
//!
//! The table covers every diagnostic raised while compiling a source text:
//! all 133 `js_parse_error*` call sites reachable from JavaScript parsing, plus
//! the `JS_ThrowSyntaxError` sites that run during compilation before any of
//! the source executes (`quickjs.c:27600`, `33354`, `35893`, `47397`, `47407`).
//!
//! Deliberately outside the table:
//!
//! - JSON parsing (`json_parse_*`, `JS_ParseJSON3`), which is a separate
//!   grammar reached only through `JSON.parse`;
//! - bytecode reader diagnostics (`quickjs.c:38303`-`39318`), which validate
//!   serialized bytecode rather than source text and are covered by the
//!   bytecode verifier contract;
//! - built-in `SyntaxError`s raised at run time by `BigInt`, `JSON.rawJSON`,
//!   and the base64/hex conversions (`quickjs.c:14642`, `49677`,
//!   `59374`-`59527`), which no source text can provoke at compile time;
//! - module link-time resolution errors (`quickjs.c:30126`-`30136`), which need
//!   a resolved module graph and belong to the pending module-linking work.

/// Whether the corpus can provoke a pinned diagnostic.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum DiagnosticReach {
    /// A corpus fixture must provoke this diagnostic from the oracle.
    Reachable,
    /// No fixture may declare it; the recorded reason explains why.
    Unreachable(&'static str),
}

/// One pinned diagnostic and the evidence that anchors it.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct PinnedDiagnostic {
    /// Stable ledger identifier used by `manifest.json`.
    pub(crate) id: &'static str,
    /// Pinned `QuickJS` format string, including runtime substitutions.
    pub(crate) message: &'static str,
    /// `quickjs.c` call sites that raise the diagnostic.
    pub(crate) sites: &'static [&'static str],
    /// Whether a fixture is required or forbidden.
    pub(crate) reach: DiagnosticReach,
    /// Claims a fixture for this diagnostic exercises.
    pub(crate) claims: &'static [&'static str],
}

/// Every pinned `QuickJS` parser diagnostic, ordered by ledger identifier.
pub(crate) const PINNED_DIAGNOSTICS: [PinnedDiagnostic; 110] = [
    PinnedDiagnostic {
        id: "arguments-in-class-field-initializer",
        message: "'arguments' identifier is not allowed in class field initializer",
        sites: &["quickjs.c:26858"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.syntax-private-super"],
    },
    PinnedDiagnostic {
        id: "assignment-rest-property-not-last",
        message: "assignment rest property must be last",
        sites: &["quickjs.c:26300"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "await-in-default-expression",
        message: "await in default expression",
        sites: &["quickjs.c:27563"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.contextual-early-errors"],
    },
    PinnedDiagnostic {
        id: "break-outside-loop-or-switch",
        message: "break must be inside loop or switch",
        sites: &["quickjs.c:28268"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.abrupt-handlers"],
    },
    PinnedDiagnostic {
        id: "class-declaration-single-statement",
        message: "class declarations can't appear in single-statement context",
        sites: &["quickjs.c:29500"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.lexical-placement-collisions"],
    },
    PinnedDiagnostic {
        id: "class-statement-requires-name",
        message: "class statement requires a name",
        sites: &["quickjs.c:25186"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.syntax-private-super"],
    },
    PinnedDiagnostic {
        id: "coalesce-mixed-with-logical",
        message: "cannot mix ?? with && or ||",
        sites: &["quickjs.c:27815"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.operators-assignment"],
    },
    PinnedDiagnostic {
        id: "const-without-initializer",
        message: "missing initializer for const variable",
        sites: &["quickjs.c:28459"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "continue-outside-loop",
        message: "continue must be inside loop",
        sites: &["quickjs.c:28266"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.abrupt-handlers"],
    },
    PinnedDiagnostic {
        id: "delete-private-field",
        message: "cannot delete a private class field",
        sites: &["quickjs.c:27458"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.syntax-private-super"],
    },
    PinnedDiagnostic {
        id: "duplicate-argument-name",
        message: "duplicate argument names not allowed in this context",
        sites: &["quickjs.c:36351"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.parameters"],
    },
    PinnedDiagnostic {
        id: "duplicate-class-constructor",
        message: "property constructor appears more than once",
        sites: &["quickjs.c:25487"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.duplicate-proto-private-early-errors"],
    },
    PinnedDiagnostic {
        id: "duplicate-exported-name",
        message: "duplicate exported name '%s'",
        sites: &["quickjs.c:29690"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.early-errors"],
    },
    PinnedDiagnostic {
        id: "duplicate-import-attribute-key",
        message: "duplicate with key",
        sites: &["quickjs.c:31525"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.attributes"],
    },
    PinnedDiagnostic {
        id: "duplicate-import-binding",
        message: "duplicate import binding",
        sites: &["quickjs.c:31760"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.early-errors"],
    },
    PinnedDiagnostic {
        id: "duplicate-label-name",
        message: "duplicate label name",
        sites: &["quickjs.c:28801"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.iteration-labels"],
    },
    PinnedDiagnostic {
        id: "duplicate-parameter-name",
        message: "duplicate parameter names not allowed in this context",
        sites: &["quickjs.c:26175"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.parameters"],
    },
    PinnedDiagnostic {
        id: "duplicate-private-field",
        message: "private class field is already defined",
        sites: &["quickjs.c:25508"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.duplicate-proto-private-early-errors"],
    },
    PinnedDiagnostic {
        id: "duplicate-proto-property",
        message: "duplicate __proto__ property name",
        sites: &["quickjs.c:24940"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.duplicate-proto-private-early-errors"],
    },
    PinnedDiagnostic {
        id: "duplicate-switch-default",
        message: "duplicate default",
        sites: &["quickjs.c:29228"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.basic-control"],
    },
    PinnedDiagnostic {
        id: "expecting-as",
        message: "expecting 'as'",
        sites: &["quickjs.c:31834", "quickjs.c:31886"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.import-export"],
    },
    PinnedDiagnostic {
        id: "expecting-field-name",
        message: "expecting field name",
        sites: &["quickjs.c:27318"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.member-call-new-optional"],
    },
    PinnedDiagnostic {
        id: "expecting-token",
        message: "expecting '%c'",
        sites: &["quickjs.c:22256", "quickjs.c:22268", "quickjs.c:25537"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "for-await-outside-async",
        message: "for await is only valid in asynchronous functions",
        sites: &["quickjs.c:29022"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.contextual-early-errors"],
    },
    PinnedDiagnostic {
        id: "for-await-requires-of",
        message: "'for await' loop should be used with 'of'",
        sites: &["quickjs.c:28672"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.iteration-labels"],
    },
    PinnedDiagnostic {
        id: "for-control-expects-of-or-in",
        message: "expected 'of' or 'in' in for control expression",
        sites: &["quickjs.c:28681"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.iteration-labels"],
    },
    PinnedDiagnostic {
        id: "for-in-of-declaration-initializer",
        message: "a declaration in the head of a for-%s loop can't have an initializer",
        sites: &["quickjs.c:28677"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.iteration-labels"],
    },
    PinnedDiagnostic {
        id: "for-of-starts-with-async",
        message: "'for of' expression cannot start with 'async'",
        sites: &["quickjs.c:28625"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.iteration-labels"],
    },
    PinnedDiagnostic {
        id: "from-clause-expected",
        message: "from clause expected",
        sites: &["quickjs.c:31554"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.import-export"],
    },
    PinnedDiagnostic {
        id: "function-declaration-single-statement",
        message: "function declarations can't appear in single-statement context",
        sites: &["quickjs.c:29486"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.lexical-placement-collisions"],
    },
    PinnedDiagnostic {
        id: "function-name-expected",
        message: "function name expected",
        sites: &["quickjs.c:36443"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.parameters"],
    },
    PinnedDiagnostic {
        id: "identifier-expected",
        message: "identifier expected",
        sites: &[
            "quickjs.c:29325",
            "quickjs.c:31496",
            "quickjs.c:31613",
            "quickjs.c:31633",
            "quickjs.c:31678",
            "quickjs.c:31838",
            "quickjs.c:31866",
            "quickjs.c:31878",
        ],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.abrupt-handlers"],
    },
    PinnedDiagnostic {
        id: "import-meta-expected",
        message: "meta expected",
        sites: &["quickjs.c:26942"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.contextual-meta-super-new-target"],
    },
    PinnedDiagnostic {
        id: "import-meta-outside-module",
        message: "import.meta only valid in module code",
        sites: &["quickjs.c:26944"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.contextual-meta-super-new-target"],
    },
    PinnedDiagnostic {
        id: "invalid-accessor-parameter-count",
        message: "invalid number of arguments for getter or setter",
        sites: &["quickjs.c:36716"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.parameters"],
    },
    PinnedDiagnostic {
        id: "invalid-assignment-syntax",
        message: "invalid assignment syntax",
        sites: &["quickjs.c:26653"],
        reach: DiagnosticReach::Unreachable(
            "every js_parse_destructuring_element caller guards on '{' or '[' (quickjs.c:26344, 26577, 28063, 28476, 28601, 28630, 29322, 36618), so the trailing else is dead",
        ),
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "invalid-assignment-target",
        message: "invalid assignment left-hand side",
        sites: &["quickjs.c:25870"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.operators-assignment"],
    },
    PinnedDiagnostic {
        id: "invalid-destructuring-target",
        message: "invalid destructuring target",
        sites: &["quickjs.c:25868", "quickjs.c:26204", "quickjs.c:26461"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "invalid-dynamic-import",
        message: "invalid use of 'import()'",
        sites: &["quickjs.c:26953"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.member-call-new-optional"],
    },
    PinnedDiagnostic {
        id: "invalid-export-syntax",
        message: "invalid export syntax",
        sites: &["quickjs.c:31736"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.import-export"],
    },
    PinnedDiagnostic {
        id: "invalid-field-name",
        message: "invalid field name",
        sites: &["quickjs.c:25396"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.duplicate-proto-private-early-errors"],
    },
    PinnedDiagnostic {
        id: "invalid-for-in-of-target",
        message: "invalid for in/of left hand-side",
        sites: &["quickjs.c:25864"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.iteration-labels"],
    },
    PinnedDiagnostic {
        id: "invalid-import-binding",
        message: "invalid import binding",
        sites: &["quickjs.c:31755"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.early-errors"],
    },
    PinnedDiagnostic {
        id: "invalid-keyword-with",
        message: "invalid keyword: with",
        sites: &["quickjs.c:29432"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.basic-control"],
    },
    PinnedDiagnostic {
        id: "invalid-lexical-variable-name",
        message: "invalid lexical variable name",
        sites: &["quickjs.c:26110"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "invalid-method-name",
        message: "invalid method name",
        sites: &["quickjs.c:25322"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.duplicate-proto-private-early-errors"],
    },
    PinnedDiagnostic {
        id: "invalid-number-literal",
        message: "invalid number literal",
        sites: &["quickjs.c:22928"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.literals-tokenization"],
    },
    PinnedDiagnostic {
        id: "invalid-private-name-start",
        message: "invalid first character of private name",
        sites: &["quickjs.c:22878"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "invalid-property-name",
        message: "invalid property name",
        sites: &["quickjs.c:24611"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.duplicate-proto-private-early-errors"],
    },
    PinnedDiagnostic {
        id: "invalid-regexp-flags",
        message: "invalid regular expression flags",
        sites: &["quickjs.c:47397"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "invalid-super-usage",
        message: "invalid use of 'super'",
        sites: &["quickjs.c:26932"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.contextual-meta-super-new-target"],
    },
    PinnedDiagnostic {
        id: "invalid-switch-statement",
        message: "invalid switch statement",
        sites: &["quickjs.c:29246"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.basic-control"],
    },
    PinnedDiagnostic {
        id: "invalid-update-operand",
        message: "invalid increment/decrement operand",
        sites: &["quickjs.c:25866"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.operators-assignment"],
    },
    PinnedDiagnostic {
        id: "invalid-utf8-sequence",
        message: "invalid UTF-8 sequence",
        sites: &["quickjs.c:22320", "quickjs.c:22471", "quickjs.c:22542"],
        reach: DiagnosticReach::Unreachable(
            "regexp literals reach this branch only for invalid UTF-8 bytes, which the corpus forbids",
        ),
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "label-not-found",
        message: "break/continue label not found",
        sites: &["quickjs.c:28270"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.iteration-labels"],
    },
    PinnedDiagnostic {
        id: "let-as-lexical-identifier",
        message: "'let' is not a valid lexical identifier",
        sites: &["quickjs.c:28412"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "lexical-declaration-single-statement",
        message: "lexical declarations can't appear in single-statement context",
        sites: &["quickjs.c:28889"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.lexical-placement-collisions"],
    },
    PinnedDiagnostic {
        id: "malformed-string-escape",
        message: "malformed escape sequence in string literal",
        sites: &["quickjs.c:22439"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "missing-binding-pattern",
        message: "missing binding pattern...",
        sites: &["quickjs.c:26556"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "missing-exported-variable",
        message: "exported variable '%s' does not exist",
        sites: &["quickjs.c:35893"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.early-errors"],
    },
    PinnedDiagnostic {
        id: "missing-formal-parameter",
        message: "missing formal parameter",
        sites: &["quickjs.c:36701"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.parameters"],
    },
    PinnedDiagnostic {
        id: "new-in-optional-chain",
        message: "new keyword cannot be used with an optional chain",
        sites: &["quickjs.c:26990"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.member-call-new-optional"],
    },
    PinnedDiagnostic {
        id: "new-target-expected",
        message: "expecting target",
        sites: &["quickjs.c:26891"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.contextual-meta-super-new-target"],
    },
    PinnedDiagnostic {
        id: "new-target-outside-function",
        message: "new.target only allowed within functions",
        sites: &["quickjs.c:26893"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.contextual-meta-super-new-target"],
    },
    PinnedDiagnostic {
        id: "parser-stack-overflow",
        message: "stack overflow",
        sites: &["quickjs.c:22720"],
        reach: DiagnosticReach::Reachable,
        claims: &["profile.parser-resource-limits"],
    },
    PinnedDiagnostic {
        id: "private-field-after-super",
        message: "private class field forbidden after super",
        sites: &["quickjs.c:27308"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.syntax-private-super"],
    },
    PinnedDiagnostic {
        id: "redefined-global-identifier",
        message: "invalid redefinition of global identifier",
        sites: &["quickjs.c:24241", "quickjs.c:36482"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.collision-early-errors"],
    },
    PinnedDiagnostic {
        id: "redefined-global-identifier-in-module",
        message: "invalid redefinition of global identifier in module code",
        sites: &["quickjs.c:36456"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.early-errors"],
    },
    PinnedDiagnostic {
        id: "redefined-lexical-identifier",
        message: "invalid redefinition of lexical identifier",
        sites: &["quickjs.c:24220", "quickjs.c:24282"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.collision-early-errors"],
    },
    PinnedDiagnostic {
        id: "redefined-parameter-name",
        message: "invalid redefinition of parameter name",
        sites: &["quickjs.c:24229"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.collision-early-errors"],
    },
    PinnedDiagnostic {
        id: "redefined-variable",
        message: "invalid redefinition of a variable",
        sites: &["quickjs.c:24233"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.collision-early-errors"],
    },
    PinnedDiagnostic {
        id: "regexp-line-terminator",
        message: "unexpected line terminator in regexp",
        sites: &["quickjs.c:22548"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "regexp-pattern-compilation",
        message: "%s",
        sites: &["quickjs.c:47407"],
        reach: DiagnosticReach::Reachable,
        claims: &["profile.regexp-pattern-delegation"],
    },
    PinnedDiagnostic {
        id: "regexp-unsupported-build",
        message: "RegExp are not supported",
        sites: &["quickjs.c:26771"],
        reach: DiagnosticReach::Unreachable(
            "qjs installs the RegExp compiler through JS_AddIntrinsicRegExpCompiler (quickjs.c:49033-49036), so compile_regexp is never null",
        ),
        claims: &["profile.regexp-pattern-delegation"],
    },
    PinnedDiagnostic {
        id: "reserved-identifier",
        message: "'%s' is a reserved identifier",
        sites: &[
            "quickjs.c:25179",
            "quickjs.c:26839",
            "quickjs.c:28408",
            "quickjs.c:29469",
            "quickjs.c:31812",
            "quickjs.c:36428",
            "quickjs.c:36566",
            "quickjs.c:36627",
            "quickjs.c:36632",
        ],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.identifiers-keywords-unicode"],
    },
    PinnedDiagnostic {
        id: "rest-element-default-value",
        message: "rest element cannot have a default value",
        sites: &["quickjs.c:26570"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "rest-element-not-last",
        message: "rest element must be the last one",
        sites: &["quickjs.c:26641"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "return-in-static-block",
        message: "return in a static initializer block",
        sites: &["quickjs.c:28848"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.syntax-private-super"],
    },
    PinnedDiagnostic {
        id: "return-outside-function",
        message: "return not in a function",
        sites: &["quickjs.c:28844"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.abrupt-handlers"],
    },
    PinnedDiagnostic {
        id: "strict-delete-identifier",
        message: "cannot delete a direct reference in strict mode",
        sites: &["quickjs.c:27452"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.strict-mode-early-errors"],
    },
    PinnedDiagnostic {
        id: "strict-directive-with-nonsimple-parameters",
        message: "\"use strict\" not allowed in function with default or destructuring parameter",
        sites: &["quickjs.c:36310"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.cover-grammar-early-errors"],
    },
    PinnedDiagnostic {
        id: "strict-invalid-argument-name",
        message: "invalid argument name in strict code",
        sites: &["quickjs.c:36321"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.strict-mode-early-errors"],
    },
    PinnedDiagnostic {
        id: "strict-invalid-function-name",
        message: "invalid function name in strict code",
        sites: &["quickjs.c:36314"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.strict-mode-early-errors"],
    },
    PinnedDiagnostic {
        id: "strict-invalid-lvalue",
        message: "invalid lvalue in strict mode",
        sites: &["quickjs.c:25836"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.strict-mode-early-errors"],
    },
    PinnedDiagnostic {
        id: "strict-invalid-variable-name",
        message: "invalid variable name in strict mode",
        sites: &["quickjs.c:26106"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.strict-mode-early-errors"],
    },
    PinnedDiagnostic {
        id: "strict-legacy-octal-literal",
        message: "octal literals are deprecated in strict mode",
        sites: &["quickjs.c:22905"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.strict-mode-early-errors"],
    },
    PinnedDiagnostic {
        id: "strict-octal-string-escape",
        message: "octal escape sequences are not allowed in strict mode",
        sites: &["quickjs.c:22419"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.strict-mode-early-errors"],
    },
    PinnedDiagnostic {
        id: "string-expected",
        message: "string expected",
        sites: &["quickjs.c:31508", "quickjs.c:31560"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.attributes"],
    },
    PinnedDiagnostic {
        id: "super-call-outside-derived-constructor",
        message: "super() is only valid in a derived class constructor",
        sites: &["quickjs.c:26919"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.contextual-meta-super-new-target"],
    },
    PinnedDiagnostic {
        id: "super-outside-method",
        message: "'super' is only valid in a method",
        sites: &["quickjs.c:26923"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.contextual-meta-super-new-target"],
    },
    PinnedDiagnostic {
        id: "template-in-optional-chain",
        message: "template literal cannot appear in an optional chain",
        sites: &["quickjs.c:27006"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.member-call-new-optional"],
    },
    PinnedDiagnostic {
        id: "throw-line-terminator",
        message: "line terminator not allowed after throw",
        sites: &["quickjs.c:28874"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.abrupt-handlers"],
    },
    PinnedDiagnostic {
        id: "too-complicated-destructuring",
        message: "too complicated destructuring expression",
        sites: &["quickjs.c:26672"],
        reach: DiagnosticReach::Unreachable(
            "the only hasval=FALSE caller (quickjs.c:28063) is guarded by js_parse_skip_parens_token finding '=', so the !hasval branch is dead",
        ),
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "too-many-call-arguments",
        message: "Too many call arguments",
        sites: &["quickjs.c:27143"],
        reach: DiagnosticReach::Reachable,
        claims: &["profile.parser-resource-limits"],
    },
    PinnedDiagnostic {
        id: "try-without-handler",
        message: "expecting catch or finally",
        sites: &["quickjs.c:29383"],
        reach: DiagnosticReach::Reachable,
        claims: &["statement.abrupt-handlers"],
    },
    PinnedDiagnostic {
        id: "undefined-private-field",
        message: "undefined private field '%s'",
        sites: &["quickjs.c:33354"],
        reach: DiagnosticReach::Reachable,
        claims: &["class.syntax-private-super"],
    },
    PinnedDiagnostic {
        id: "unexpected-await-keyword",
        message: "unexpected 'await' keyword",
        sites: &["quickjs.c:27561"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.contextual-early-errors"],
    },
    PinnedDiagnostic {
        id: "unexpected-character",
        message: "unexpected character",
        sites: &["quickjs.c:23134"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "unexpected-end-of-comment",
        message: "unexpected end of comment",
        sites: &["quickjs.c:22770"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.comments-hashbang-html"],
    },
    PinnedDiagnostic {
        id: "unexpected-end-of-regexp",
        message: "unexpected end of regexp",
        sites: &["quickjs.c:22505"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "unexpected-end-of-string",
        message: "unexpected end of string",
        sites: &["quickjs.c:22338", "quickjs.c:22475"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "unexpected-token-in-expression",
        message: "unexpected token in expression: '%.*s'",
        sites: &["quickjs.c:26979"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "unexpected-yield-keyword",
        message: "unexpected 'yield' keyword",
        sites: &["quickjs.c:27892"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.contextual-early-errors"],
    },
    PinnedDiagnostic {
        id: "unpaired-surrogate-module-name",
        message: "contains unpaired surrogate",
        sites: &["quickjs.c:31625", "quickjs.c:31857"],
        reach: DiagnosticReach::Reachable,
        claims: &["module.early-errors"],
    },
    PinnedDiagnostic {
        id: "unparenthesized-unary-before-exponentiation",
        message: "unparenthesized unary expression can't appear on the left-hand side of '**'",
        sites: &["quickjs.c:27600"],
        reach: DiagnosticReach::Reachable,
        claims: &["expression.operators-assignment"],
    },
    PinnedDiagnostic {
        id: "unsupported-keyword",
        message: "unsupported keyword: %s",
        sites: &["quickjs.c:26092"],
        reach: DiagnosticReach::Reachable,
        claims: &["profile.rejected-outside-target"],
    },
    PinnedDiagnostic {
        id: "unterminated-template-substitution",
        message: "expected '}' after template expression",
        sites: &["quickjs.c:24458"],
        reach: DiagnosticReach::Reachable,
        claims: &["lexical.malformed-token-rejections"],
    },
    PinnedDiagnostic {
        id: "variable-name-expected",
        message: "variable name expected",
        sites: &["quickjs.c:28479", "quickjs.c:28605"],
        reach: DiagnosticReach::Reachable,
        claims: &["binding.declarations-patterns"],
    },
    PinnedDiagnostic {
        id: "yield-in-default-expression",
        message: "yield in default expression",
        sites: &["quickjs.c:27894"],
        reach: DiagnosticReach::Reachable,
        claims: &["function.contextual-early-errors"],
    },
    PinnedDiagnostic {
        id: "yield-reserved-identifier",
        message: "yield is a reserved identifier",
        sites: &["quickjs.c:26102"],
        reach: DiagnosticReach::Unreachable(
            "js_define_var sees `yield` in a generator only through TOK_IDENT; unescaped `yield` tokenizes as TOK_YIELD and escaped spellings set is_reserved, which earlier checks reject",
        ),
        claims: &["function.contextual-early-errors"],
    },
];
