[package]
name = "fusor-intl"
version = "0.0.1"
description = "ECMA-402 locale algorithms backed directly by ICU4X"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
fixed_decimal.workspace = true
icu = { workspace = true, features = ["compiled_data", "unstable"] }
writeable.workspace = true

[lints]
workspace = true
