//! Op binding layer (§5): declarations, the op error contract, and the
//! assembly registry.

use std::collections::HashMap;

/// Static declaration metadata for one `#[op]` function.
///
/// Generated by the `fusor_ops::op` attribute macro and consumed by
/// [`OpRegistry`] at assembly time. The `name` is the op's original
/// snake_case function name unless overridden with `#[op(name = "...")]`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpDeclaration {
    /// The op name installed as `Fusor.ops.<name>`.
    pub name: &'static str,
    /// The Rust parameter type names in declaration order (lossy text used
    /// for diagnostics; the runtime contract is the generated adapter).
    pub parameter_types: &'static [&'static str],
    /// Whether the op function is `async` (settles a host Promise).
    pub is_async: bool,
}

/// The op-level error contract (§5.3).
///
/// An op returns this when its operation fails in a way JavaScript should
/// observe. The host adapter converts it into a thrown JavaScript error of
/// `class` (default `Error`) carrying `message`; `code` is an optional
/// machine-readable code attached for diagnostics.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OpError {
    /// The JavaScript error class name (`"TypeError"`, `"RangeError"`,
    /// `"SyntaxError"`); `None` means `"Error"`.
    pub class: Option<&'static str>,
    /// The exact error message the JavaScript side observes.
    pub message: String,
    /// An optional stable machine-readable error code.
    pub code: Option<&'static str>,
}

impl OpError {
    /// Creates a plain `Error`-class op error.
    #[must_use]
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            class: None,
            message: message.into(),
            code: None,
        }
    }

    /// Creates an op error of the given JavaScript error class.
    #[must_use]
    pub fn of_class(class: &'static str, message: impl Into<String>) -> Self {
        Self {
            class: Some(class),
            message: message.into(),
            code: None,
        }
    }

    /// Attaches a stable machine-readable error code.
    #[must_use]
    pub const fn with_code(mut self, code: &'static str) -> Self {
        self.code = Some(code);
        self
    }

    /// Creates the argument-deserialization failure: a `TypeError` naming the
    /// zero-based parameter index (§5.2).
    #[must_use]
    pub fn type_error(parameter: usize, message: impl Into<String>) -> Self {
        Self {
            class: Some("TypeError"),
            message: format!("parameter {parameter}: {}", message.into()),
            code: None,
        }
    }
}

impl std::fmt::Display for OpError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.class {
            Some(class) => write!(formatter, "{class}: {}", self.message),
            None => formatter.write_str(&self.message),
        }
    }
}

impl std::error::Error for OpError {}

/// Assembly-time op registry: collects declarations, detects name conflicts
/// between overlays before any JavaScript runs (§5.4).
#[derive(Debug, Default)]
pub struct OpRegistry {
    entries: HashMap<&'static str, OpDeclaration>,
}

impl OpRegistry {
    /// Creates an empty registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers one op declaration.
    ///
    /// # Errors
    ///
    /// Returns the previous declaration when another overlay already
    /// registered the same op name; assembly must fail closed on the
    /// conflict (§5.4: same-name conflicts are a build-time error).
    pub fn register(
        &mut self,
        declaration: OpDeclaration,
    ) -> Result<(), OpDeclarationConflict> {
        if let Some(previous) = self.entries.get(declaration.name) {
            return Err(OpDeclarationConflict {
                name: declaration.name,
                previous: *previous,
            });
        }
        self.entries.insert(declaration.name, declaration);
        Ok(())
    }

    /// Returns the registered declaration for an op name.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&OpDeclaration> {
        self.entries.get(name)
    }

    /// Iterates the registered declarations in registration order.
    pub fn declarations(&self) -> impl Iterator<Item = &OpDeclaration> {
        self.entries.values()
    }
}

/// A same-name op conflict between two overlays (§5.4: detected at assembly
/// time, never at runtime).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpDeclarationConflict {
    /// The conflicting op name.
    pub name: &'static str,
    /// The declaration that was registered first.
    pub previous: OpDeclaration,
}

impl std::fmt::Display for OpDeclarationConflict {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "op name '{}' is declared more than once",
            self.name
        )
    }
}

impl std::error::Error for OpDeclarationConflict {}
