//! Op binding layer (§5): declarations, the op error contract, and the
//! assembly registry.

mod op_runtime;
mod process;
mod resources;
mod serde;
mod timers;

pub use op_runtime::{
    OpRuntime, OpRuntimeError, install_op_runtime, pending_op_count, poll_op_completions,
    spawn_op, take_op_runtime,
};
pub use process::install_process;
pub use resources::{
    Resource, ResourceId, ResourceTable, ResourceTableError,
};
pub use serde::{DeserializationError, JsValueDeserializer, JsValueSerializer, SerializationError};
pub use timers::install_timers;

use fusor_runtime::{Context, JsValue};
use std::collections::HashMap;
use std::rc::Rc;

thread_local! {
    static RESOURCE_TABLE: std::cell::RefCell<ResourceTable> =
        std::cell::RefCell::new(ResourceTable::new());
}

/// Installs the host-runtime-wide resource table shared by every op (§5.6).
///
/// # Errors
///
/// Returns the table unchanged when one is already installed.
pub fn install_resource_table(table: ResourceTable) -> Result<(), ResourceTable> {
    RESOURCE_TABLE.with(|slot| {
        if !slot.borrow().is_empty() {
            return Err(table);
        }
        *slot.borrow_mut() = table;
        Ok(())
    })
}

/// Looks up one live resource through the installed table (the
/// `ResourceId`-parameter specialization of the `#[op]` macro).
#[must_use]
pub fn lookup_resource(id: u32) -> Option<Rc<dyn Resource>> {
    RESOURCE_TABLE.with(|slot| {
        slot.borrow()
            .get(ResourceId::from_u32(id))
            .cloned()
    })
}

/// Adds one resource to the installed table (host bootstrap path).
///
/// # Errors
///
/// Returns the resource unchanged when the id domain is exhausted.
pub fn add_resource(
    resource: Rc<dyn Resource>,
) -> Result<ResourceId, resources::ResourceTableError> {
    RESOURCE_TABLE.with(|slot| slot.borrow_mut().add(resource))
}

/// Closes one resource in the installed table (the JS-side close op path).
#[must_use]
pub fn close_resource(id: u32) -> bool {
    RESOURCE_TABLE.with(|slot| slot.borrow_mut().close(ResourceId::from_u32(id)))
}

/// Closes every table-exclusive resource in the installed table
/// (shutdown step ③, §7.4) and returns the number of live entries taken.
///
/// Resources still held elsewhere (an embedder `Rc`, a live async-op
/// future) close when their last holder drops, per the [`Resource`]
/// contract.
#[must_use]
pub fn close_all_resources() -> usize {
    RESOURCE_TABLE.with(|slot| {
        let mut table = slot.borrow_mut();
        let count = table.len();
        table.close_all();
        count
    })
}

/// Static declaration metadata for one `#[op]` function.
///
/// Generated by the `fusor_ops::op` attribute macro and consumed by
/// [`OpRegistry`] at assembly time. The `name` is the op's original
/// snake_case function name unless overridden with `#[op(name = "...")]`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpDeclaration {
    /// The op name installed as `Fusor.ops.<name>`.
    pub name: &'static str,
    /// The Rust parameter type names in declaration order (lossy text used
    /// for diagnostics; the runtime contract is the generated adapter).
    pub parameter_types: &'static [&'static str],
    /// Whether the op function is `async` (settles a host Promise).
    pub is_async: bool,
}

/// The op-level error contract (§5.3).
///
/// An op returns this when its operation fails in a way JavaScript should
/// observe. The host adapter converts it into a thrown JavaScript error of
/// `class` (default `Error`) carrying `message`; `code` is an optional
/// numeric machine-readable error code attached for diagnostics (§12.1:
/// plain numbers, op-layer range 14000–14099).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OpError {
    /// The JavaScript error class name (`"TypeError"`, `"RangeError"`,
    /// `"SyntaxError"`); `None` means `"Error"`.
    pub class: Option<&'static str>,
    /// The exact error message the JavaScript side observes.
    pub message: String,
    /// An optional numeric machine-readable error code (§12.1).
    pub code: Option<u16>,
}

impl OpError {
    /// Creates a plain `Error`-class op error.
    #[must_use]
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            class: None,
            message: message.into(),
            code: None,
        }
    }

    /// Creates an op error of the given JavaScript error class.
    #[must_use]
    pub fn of_class(class: &'static str, message: impl Into<String>) -> Self {
        Self {
            class: Some(class),
            message: message.into(),
            code: None,
        }
    }

    /// Attaches a numeric machine-readable error code (§12.1).
    #[must_use]
    pub const fn with_code(mut self, code: u16) -> Self {
        self.code = Some(code);
        self
    }

    /// Creates the argument-deserialization failure: a `TypeError` naming the
    /// zero-based parameter index (§5.2).
    #[must_use]
    pub fn type_error(parameter: usize, message: impl Into<String>) -> Self {
        Self {
            class: Some("TypeError"),
            message: format!("parameter {parameter}: {}", message.into()),
            code: None,
        }
    }
}

impl std::fmt::Display for OpError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.class {
            Some(class) => write!(formatter, "{class}: {}", self.message),
            None => formatter.write_str(&self.message),
        }
    }
}

impl std::error::Error for OpError {}

/// Assembly-time op registry: collects declarations, detects name conflicts
/// between overlays before any JavaScript runs (§5.4).
#[derive(Debug, Default)]
pub struct OpRegistry {
    entries: HashMap<&'static str, OpDeclaration>,
}

impl OpRegistry {
    /// Creates an empty registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers one op declaration.
    ///
    /// # Errors
    ///
    /// Returns the previous declaration when another overlay already
    /// registered the same op name; assembly must fail closed on the
    /// conflict (§5.4: same-name conflicts are a build-time error).
    pub fn register(
        &mut self,
        declaration: OpDeclaration,
    ) -> Result<(), OpDeclarationConflict> {
        if let Some(previous) = self.entries.get(declaration.name) {
            return Err(OpDeclarationConflict {
                name: declaration.name,
                previous: *previous,
            });
        }
        self.entries.insert(declaration.name, declaration);
        Ok(())
    }

    /// Returns the registered declaration for an op name.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&OpDeclaration> {
        self.entries.get(name)
    }

    /// Iterates the registered declarations in registration order.
    pub fn declarations(&self) -> impl Iterator<Item = &OpDeclaration> {
        self.entries.values()
    }
}

/// A same-name op conflict between two overlays (§5.4: detected at assembly
/// time, never at runtime).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpDeclarationConflict {
    /// The conflicting op name.
    pub name: &'static str,
    /// The declaration that was registered first.
    pub previous: OpDeclaration,
}

impl std::fmt::Display for OpDeclarationConflict {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "op name '{}' is declared more than once",
            self.name
        )
    }
}

impl std::error::Error for OpDeclarationConflict {}

/// Serializes one op result through the serde bridge (§5.2).
///
/// A serialization failure becomes a thrown `InternalError`: the op already
/// produced a value the bridge cannot represent, which is a host bug, not a
/// JavaScript misuse.
pub fn serialize_value<T: ::serde::Serialize>(
    context: &mut Context<'_>,
    value: &T,
) -> Result<JsValue, JsValue> {
    ::serde::Serialize::serialize(value, JsValueSerializer::new(context))
        .map_err(|error| op_error_value(context, OpError::of_class("InternalError", error.to_string())))
}

/// Converts an op error into the JavaScript error value it throws (§5.3):
/// the class names the intrinsic Error family (`Error` by default) and the
/// message is preserved exactly.
pub fn op_error_value(context: &mut Context<'_>, error: OpError) -> JsValue {
    let kind = match error.class {
        None | Some("Error") => fusor_runtime::ErrorObjectKind::Error,
        Some("TypeError") => fusor_runtime::ErrorObjectKind::TypeError,
        Some("RangeError") => fusor_runtime::ErrorObjectKind::RangeError,
        Some("SyntaxError") => fusor_runtime::ErrorObjectKind::SyntaxError,
        Some("ReferenceError") => fusor_runtime::ErrorObjectKind::ReferenceError,
        Some("UriError") | Some("URIError") => fusor_runtime::ErrorObjectKind::UriError,
        Some("InternalError") => fusor_runtime::ErrorObjectKind::InternalError,
        // Unknown classes fall back to plain Error (fail closed, §5.3).
        Some(_) => fusor_runtime::ErrorObjectKind::Error,
    };
    context
        .error(kind, &error.message)
        .unwrap_or_else(|_| context.undefined())
}

/// Installs the `Fusor` namespace object and its `Fusor.ops` sub-object on
/// the realm global (§5.4).
///
/// Both objects are installed as non-writable, non-enumerable,
/// non-configurable data properties, exactly once per realm.
///
/// # Errors
///
/// Returns an [`ExecutionError`] when the global refuses the definitions
/// (for example a frozen global) or allocation fails.
pub fn install_namespace(context: &mut Context<'_>) -> Result<(), fusor_runtime::ExecutionError> {
    let global = context.global_object()?.into_object()?;
    let fusor_key = context.property_key("Fusor")?;
    let ops_key = context.property_key("ops")?;
    // Repeated installation is idempotent: the non-configurable namespace
    // property cannot be redefined, so an existing namespace is reused as-is.
    if global.has(context, fusor_key.clone())? {
        return Ok(());
    }
    let fusor = context.new_object()?;
    let ops = context.new_object()?;
    let descriptor = |value: JsValue| {
        let fields = fusor_runtime::DescriptorFields::<JsValue> {
            value: Some(value),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(false),
            ..fusor_runtime::DescriptorFields::new()
        };
        fields
            .into_descriptor()
            .map_err(|_| fusor_runtime::EngineFault::RuntimeInvariant {
                message: "namespace descriptor is data-only by construction",
            })
            .map_err(fusor_runtime::ExecutionError::from)
    };
    if !global.define_own_property(context, fusor_key, descriptor(fusor.clone())?)? {
        return Err(fusor_runtime::EngineFault::RuntimeInvariant {
            message: "the global refused the Fusor namespace definition",
        }
        .into());
    }
    let fusor_object = fusor.into_object()?;
    if !fusor_object.define_own_property(context, ops_key, descriptor(ops.clone())?)? {
        return Err(fusor_runtime::EngineFault::RuntimeInvariant {
            message: "the Fusor namespace refused its ops sub-object",
        }
        .into());
    }
    Ok(())
}

/// Installs one op as `Fusor.ops.<name>` using its generated calling glue
/// (§5.4, §5.7).
///
/// The glue function has the shape
/// `Fn(&mut Context, HostCall) -> Result<JsValue, JsValue>`.
///
/// # Errors
///
/// Returns an [`ExecutionError`] when the host function cannot be created
/// or the ops object refuses the property.
pub fn install_op<F>(
    context: &mut Context<'_>,
    declaration: OpDeclaration,
    glue: F,
) -> Result<(), fusor_runtime::ExecutionError>
where
    F: fusor_runtime::HostCallback + 'static,
{
    let function = context.create_host_function(declaration.name, glue)?;
    let global = context.global_object()?.into_object()?;
    let fusor_key = context.property_key("Fusor")?;
    let ops_key = context.property_key("ops")?;
    let fusor = global.get(context, fusor_key)?.into_object()?;
    let ops = fusor.get(context, ops_key)?.into_object()?;
    define_op_on(context, ops, declaration, function.as_value())
}

/// The shared installation tail: defines one op function on a target
/// object as a writable, enumerable, configurable data property (§5.4).
pub(crate) fn define_op_on(
    context: &mut Context<'_>,
    target: fusor_runtime::Object,
    declaration: OpDeclaration,
    function: JsValue,
) -> Result<(), fusor_runtime::ExecutionError> {
    let op_key = context.property_key(declaration.name)?;
    let descriptor = fusor_runtime::DescriptorFields::<JsValue> {
        value: Some(function),
        writable: Some(true),
        enumerable: Some(true),
        configurable: Some(true),
        ..fusor_runtime::DescriptorFields::new()
    }
    .into_descriptor()
    .map_err(|_| fusor_runtime::EngineFault::RuntimeInvariant {
        message: "op descriptor is data-only by construction",
    })?;
    if !target.define_own_property(context, op_key, descriptor)? {
        return Err(fusor_runtime::EngineFault::RuntimeInvariant {
            message: "the target object refused an op definition",
        }
        .into());
    }
    Ok(())
}
