//! Op binding layer (§5): declarations, the op error contract, and the
//! assembly registry.

mod core;
mod op_runtime;
mod process;
mod resources;
mod serde;
mod state;
mod timers;

pub use core::set_print_sink;
pub(crate) use core::{install_clock_state, op_core_gc, op_core_now, op_core_print};
pub(crate) use process::install_process;
pub use state::{OpStateError, OpStateRegistry};
pub(crate) use timers::{
    op_clear_interval, op_clear_timeout, op_queue_microtask, op_set_immediate, op_set_interval,
    op_set_timeout,
};

pub use op_runtime::{
    OpRuntime, OpRuntimeError, install_op_runtime, pending_op_count, poll_op_completions, spawn_op,
    take_op_runtime,
};
pub use resources::{Resource, ResourceId, ResourceTable, ResourceTableError};
pub use serde::{DeserializationError, JsValueDeserializer, JsValueSerializer, SerializationError};

use fusor_runtime::{Context, HostCall, JsValue};
use std::collections::HashMap;
use std::rc::Rc;

/// Installs the host-runtime-wide resource table shared by every op
/// (§5.6) into the op-state registry.
///
/// # Errors
///
/// Returns the table unchanged when one is already installed.
pub fn install_resource_table(table: ResourceTable) -> Result<(), ResourceTable> {
    OpStateRegistry::install(table)
}

/// Looks up one live resource through the installed table (the
/// `ResourceId`-parameter specialization of the `#[op]` macro).
#[must_use]
pub fn lookup_resource(id: u32) -> Option<Rc<dyn Resource>> {
    OpStateRegistry::with::<ResourceTable, _>(|table| table.get(ResourceId::from_u32(id)).cloned())
        .ok()
        .flatten()
}

/// Adds one resource to the installed table (host bootstrap path).
///
/// # Errors
///
/// Returns [`ResourceTableError::NotInstalled`] when no table is
/// installed and [`ResourceTableError::IdDomainExhausted`] when the id
/// domain is exhausted.
pub fn add_resource(
    resource: Rc<dyn Resource>,
) -> Result<ResourceId, resources::ResourceTableError> {
    OpStateRegistry::with_mut::<ResourceTable, _>(|table| table.add(resource))
        .map_err(|_| resources::ResourceTableError::NotInstalled)?
}

/// Closes one resource in the installed table (the JS-side close op path).
#[must_use]
pub fn close_resource(id: u32) -> bool {
    OpStateRegistry::with_mut::<ResourceTable, _>(|table| table.close(ResourceId::from_u32(id)))
        .unwrap_or(false)
}

/// Closes every table-exclusive resource in the installed table
/// (shutdown step ③, §7.4) and returns the number of live entries taken.
///
/// Resources still held elsewhere (an embedder `Rc`, a live async-op
/// future) close when their last holder drops, per the [`Resource`]
/// contract.
#[must_use]
pub fn close_all_resources() -> usize {
    OpStateRegistry::with_mut::<ResourceTable, _>(|table| {
        let count = table.len();
        table.close_all();
        count
    })
    .unwrap_or(0)
}

/// Static declaration metadata for one `#[op]` function.
///
/// Generated by the `fusor_ops::op` attribute macro and consumed by
/// [`OpRegistry`] at assembly time. The `name` is the op's original
/// snake_case function name unless overridden with `#[op(name = "...")]`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpDeclaration {
    /// The op name installed as `Fusor.ops.<name>`.
    pub name: &'static str,
    /// The Rust parameter type names in declaration order (lossy text used
    /// for diagnostics; the runtime contract is the generated adapter).
    pub parameter_types: &'static [&'static str],
    /// Whether the op function is `async` (settles a host Promise).
    pub is_async: bool,
}

/// The op-level error contract (§5.3).
///
/// An op returns this when its operation fails in a way JavaScript should
/// observe. The host adapter converts it into a thrown JavaScript error of
/// `class` (default `Error`) carrying `message`; `code` is an optional
/// numeric machine-readable error code attached for diagnostics (§12.1:
/// plain numbers, op-layer range 14000–14099).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OpError {
    /// The JavaScript error class name (`"TypeError"`, `"RangeError"`,
    /// `"SyntaxError"`); `None` means `"Error"`.
    pub class: Option<&'static str>,
    /// The exact error message the JavaScript side observes.
    pub message: String,
    /// An optional numeric machine-readable error code (§12.1).
    pub code: Option<u16>,
}

impl OpError {
    /// Creates a plain `Error`-class op error.
    #[must_use]
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            class: None,
            message: message.into(),
            code: None,
        }
    }

    /// Creates an op error of the given JavaScript error class.
    #[must_use]
    pub fn of_class(class: &'static str, message: impl Into<String>) -> Self {
        Self {
            class: Some(class),
            message: message.into(),
            code: None,
        }
    }

    /// Attaches a numeric machine-readable error code (§12.1).
    #[must_use]
    pub const fn with_code(mut self, code: u16) -> Self {
        self.code = Some(code);
        self
    }

    /// Creates the argument-deserialization failure: a `TypeError` naming the
    /// zero-based parameter index (§5.2).
    #[must_use]
    pub fn type_error(parameter: usize, message: impl Into<String>) -> Self {
        Self {
            class: Some("TypeError"),
            message: format!("parameter {parameter}: {}", message.into()),
            code: None,
        }
    }
}

impl std::fmt::Display for OpError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.class {
            Some(class) => write!(formatter, "{class}: {}", self.message),
            None => formatter.write_str(&self.message),
        }
    }
}

impl std::error::Error for OpError {}

/// The calling glue of one registered op: the `#[op]`-generated adapter
/// that deserializes the arguments, invokes the op function, and
/// serializes the result (§5.7).
pub type OpGlue = fn(&mut Context<'_>, HostCall) -> Result<JsValue, JsValue>;

/// One op registration: its declaration plus the calling glue the assembly
/// builder installs onto `Fusor.ops` (§9 step 2).
#[derive(Clone, Copy, Debug)]
struct RegisteredOp {
    declaration: OpDeclaration,
    glue: OpGlue,
}

/// Assembly-time op registry: collects declarations, detects name conflicts
/// between overlays before any JavaScript runs (§5.4).
///
/// The [`Overlay`](crate::overlay::Overlay) ops hook registers through this
/// type. Registrations are kept in registration order (deterministic
/// installation and snapshot layout); same-name conflicts are recorded and
/// surfaced by the assembly builder through [`Self::take_conflict`] after
/// each overlay registers (fail closed).
#[derive(Debug, Default)]
pub struct OpRegistry {
    entries: Vec<RegisteredOp>,
    index: HashMap<&'static str, usize>,
    conflict: Option<OpDeclarationConflict>,
}

impl OpRegistry {
    /// Creates an empty registry.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Registers one op declaration and its calling glue.
    ///
    /// A same-name registration is recorded as a conflict (§5.4:
    /// same-name conflicts are a build-time error) and ignored;
    /// [`Self::take_conflict`] reports the recorded conflict.
    pub fn register(&mut self, declaration: OpDeclaration, glue: OpGlue) {
        if let Some(&position) = self.index.get(declaration.name) {
            if self.conflict.is_none() {
                self.conflict = Some(OpDeclarationConflict {
                    name: declaration.name,
                    previous: self.entries[position].declaration,
                });
            }
            return;
        }
        self.index.insert(declaration.name, self.entries.len());
        self.entries.push(RegisteredOp { declaration, glue });
    }

    /// Takes the first recorded same-name conflict, if any.
    #[must_use]
    pub fn take_conflict(&mut self) -> Option<OpDeclarationConflict> {
        self.conflict.take()
    }

    /// Returns the registered declaration for an op name.
    #[must_use]
    pub fn get(&self, name: &str) -> Option<&OpDeclaration> {
        self.index
            .get(name)
            .map(|&position| &self.entries[position].declaration)
    }

    /// Iterates the registered (declaration, glue) pairs in registration
    /// order, ready for installation onto `Fusor.ops` (§9 step 2).
    pub fn registrations(&self) -> impl Iterator<Item = (OpDeclaration, OpGlue)> + '_ {
        self.entries
            .iter()
            .map(|registered| (registered.declaration, registered.glue))
    }
}

/// A same-name op conflict between two overlays (§5.4: detected at assembly
/// time, never at runtime).
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpDeclarationConflict {
    /// The conflicting op name.
    pub name: &'static str,
    /// The declaration that was registered first.
    pub previous: OpDeclaration,
}

impl std::fmt::Display for OpDeclarationConflict {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            formatter,
            "op name '{}' is declared more than once",
            self.name
        )
    }
}

impl std::error::Error for OpDeclarationConflict {}

/// Serializes one op result through the serde bridge (§5.2).
///
/// A serialization failure becomes a thrown `InternalError`: the op already
/// produced a value the bridge cannot represent, which is a host bug, not a
/// JavaScript misuse.
pub fn serialize_value<T: ::serde::Serialize>(
    context: &mut Context<'_>,
    value: &T,
) -> Result<JsValue, JsValue> {
    ::serde::Serialize::serialize(value, JsValueSerializer::new(context)).map_err(|error| {
        op_error_value(
            context,
            OpError::of_class("InternalError", error.to_string()),
        )
    })
}

/// Converts an op error into the JavaScript error value it throws (§5.3):
/// the class names the intrinsic Error family (`Error` by default) and the
/// message is preserved exactly.
pub fn op_error_value(context: &mut Context<'_>, error: OpError) -> JsValue {
    let kind = match error.class {
        None | Some("Error") => fusor_runtime::ErrorObjectKind::Error,
        Some("TypeError") => fusor_runtime::ErrorObjectKind::TypeError,
        Some("RangeError") => fusor_runtime::ErrorObjectKind::RangeError,
        Some("SyntaxError") => fusor_runtime::ErrorObjectKind::SyntaxError,
        Some("ReferenceError") => fusor_runtime::ErrorObjectKind::ReferenceError,
        Some("UriError") | Some("URIError") => fusor_runtime::ErrorObjectKind::UriError,
        Some("InternalError") => fusor_runtime::ErrorObjectKind::InternalError,
        // Unknown classes fall back to plain Error (fail closed, §5.3).
        Some(_) => fusor_runtime::ErrorObjectKind::Error,
    };
    context
        .error(kind, &error.message)
        .unwrap_or_else(|_| context.undefined())
}

/// Installs the `Fusor` namespace object and its `Fusor.ops` sub-object on
/// the realm global (§5.4).
///
/// Both objects are installed as non-writable, non-enumerable,
/// non-configurable data properties, exactly once per realm. The assembly
/// builder (`HostRuntime::builder()`, §9) performs this installation as a
/// fixed host-core step; embedders never call it directly.
///
/// # Errors
///
/// Returns an [`ExecutionError`] when the global refuses the definitions
/// (for example a frozen global) or allocation fails.
pub(crate) fn install_namespace(
    context: &mut Context<'_>,
) -> Result<(), fusor_runtime::ExecutionError> {
    let global = context.global_object()?.into_object()?;
    let fusor_key = context.property_key("Fusor")?;
    let ops_key = context.property_key("ops")?;
    // Repeated installation is idempotent: the non-configurable namespace
    // property cannot be redefined, so an existing namespace is reused as-is.
    if global.has(context, fusor_key.clone())? {
        return Ok(());
    }
    let fusor = context.new_object()?;
    let ops = context.new_object()?;
    let descriptor = |value: JsValue| {
        let fields = fusor_runtime::DescriptorFields::<JsValue> {
            value: Some(value),
            writable: Some(false),
            enumerable: Some(false),
            configurable: Some(false),
            ..fusor_runtime::DescriptorFields::new()
        };
        fields
            .into_descriptor()
            .map_err(|_| fusor_runtime::EngineFault::RuntimeInvariant {
                message: "namespace descriptor is data-only by construction",
            })
            .map_err(fusor_runtime::ExecutionError::from)
    };
    if !global.define_own_property(context, fusor_key, descriptor(fusor.clone())?)? {
        return Err(fusor_runtime::EngineFault::RuntimeInvariant {
            message: "the global refused the Fusor namespace definition",
        }
        .into());
    }
    let fusor_object = fusor.into_object()?;
    if !fusor_object.define_own_property(context, ops_key, descriptor(ops.clone())?)? {
        return Err(fusor_runtime::EngineFault::RuntimeInvariant {
            message: "the Fusor namespace refused its ops sub-object",
        }
        .into());
    }
    Ok(())
}

/// Installs one op as `Fusor.ops.<name>` using its generated calling glue
/// (§5.4, §5.7).
///
/// The glue function has the shape
/// `Fn(&mut Context, HostCall) -> Result<JsValue, JsValue>`.
///
/// # Errors
///
/// Returns an [`ExecutionError`] when the host function cannot be created
/// or the ops object refuses the property.
pub fn install_op<F>(
    context: &mut Context<'_>,
    declaration: OpDeclaration,
    glue: F,
) -> Result<(), fusor_runtime::ExecutionError>
where
    F: fusor_runtime::HostCallback + 'static,
{
    let function = context.create_host_function(declaration.name, glue)?;
    let global = context.global_object()?.into_object()?;
    let fusor_key = context.property_key("Fusor")?;
    let ops_key = context.property_key("ops")?;
    let fusor = global.get(context, fusor_key)?.into_object()?;
    let ops = fusor.get(context, ops_key)?.into_object()?;
    define_op_on(context, ops, declaration, function.as_value())
}

/// The shared installation tail: defines one op function on a target
/// object as a writable, enumerable, configurable data property (§5.4).
pub(crate) fn define_op_on(
    context: &mut Context<'_>,
    target: fusor_runtime::Object,
    declaration: OpDeclaration,
    function: JsValue,
) -> Result<(), fusor_runtime::ExecutionError> {
    let op_key = context.property_key(declaration.name)?;
    let descriptor = fusor_runtime::DescriptorFields::<JsValue> {
        value: Some(function),
        writable: Some(true),
        enumerable: Some(true),
        configurable: Some(true),
        ..fusor_runtime::DescriptorFields::new()
    }
    .into_descriptor()
    .map_err(|_| fusor_runtime::EngineFault::RuntimeInvariant {
        message: "op descriptor is data-only by construction",
    })?;
    if !target.define_own_property(context, op_key, descriptor)? {
        return Err(fusor_runtime::EngineFault::RuntimeInvariant {
            message: "the target object refused an op definition",
        }
        .into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    //! Fusor namespace installation and op exposure (§5.4, §5.5): the
    //! installation primitives the assembly builder (§9) drives.

    use std::sync::Arc;

    use fusor_compiler::CompilationContext;
    use fusor_frontend::{CompilationGoal, FrontendOptions, GlobalScriptGoal, with_parsed_program};
    use fusor_ops::op;
    use fusor_runtime::{Context, ExecutionLimits, Runtime, RuntimeLimits};

    use super::{OpError, install_namespace, install_op};

    #[op]
    fn op_add(left: i32, right: i32) -> Result<i32, OpError> {
        Ok(left + right)
    }

    #[op]
    fn op_greet(name: String) -> Result<String, OpError> {
        Ok(format!("hello {name}"))
    }

    #[op]
    fn op_fail() -> Result<(), OpError> {
        Err(OpError::of_class("RangeError", "out of range"))
    }

    fn compile_global_script(source: &str) -> Arc<fusor_bytecode::VerifiedBytecode> {
        with_parsed_program(
            source,
            FrontendOptions::for_goal(CompilationGoal::GlobalScript(GlobalScriptGoal::new())),
            |unit| {
                let context =
                    CompilationContext::new_with_source_name(unit, Arc::from("fusor-namespace.js"))
                        .expect("storage plan");
                let tree = context
                    .compile_global_script(fusor_bytecode::VerificationLimits::default())
                    .expect("verified Global Script");
                Arc::new(tree.verified_bytecode().clone())
            },
        )
        .expect("frontend")
    }

    fn script_text(context: &mut Context<'_>, source: &str) -> String {
        let authority = compile_global_script(source);
        let result = context
            .execute_global_script(authority, ExecutionLimits::default())
            .expect("script");
        result
            .as_string()
            .expect("live string")
            .expect("String")
            .to_utf8_lossy()
            .expect("UTF-8")
    }

    fn with_context<T>(operation: impl FnOnce(&mut Context<'_>) -> T) -> T {
        let mut runtime = Runtime::try_new(RuntimeLimits::default()).expect("runtime");
        let realm = runtime.create_realm().expect("realm");
        let mut context = runtime.context(&realm).expect("context");
        operation(&mut context)
    }

    #[test]
    fn the_fusor_namespace_installs_with_the_spec_shape() {
        with_context(|context| {
            install_namespace(context).expect("namespace");
            assert_eq!(
                script_text(
                    context,
                    "var f = Object.getOwnPropertyDescriptor(globalThis, 'Fusor');\
                     var o = Object.getOwnPropertyDescriptor(Fusor, 'ops');\
                     JSON.stringify({\
                         present: f !== undefined,\
                         writable: f.writable,\
                         enumerable: f.enumerable,\
                         configurable: f.configurable,\
                         opsPresent: o !== undefined,\
                         opsWritable: o.writable,\
                         opsConfigurable: o.configurable,\
                         opsObject: typeof Fusor.ops === 'object',\
                     });",
                ),
                "{\"present\":true,\"writable\":false,\"enumerable\":false,\"configurable\":false,\
                 \"opsPresent\":true,\"opsWritable\":false,\"opsConfigurable\":false,\"opsObject\":true}"
            );
        });
    }

    #[test]
    fn installed_ops_are_callable_from_javascript() {
        with_context(|context| {
            install_namespace(context).expect("namespace");
            install_op(context, op_add::declaration(), op_add::call).expect("add");
            install_op(context, op_greet::declaration(), op_greet::call).expect("greet");
            install_op(context, op_fail::declaration(), op_fail::call).expect("fail");

            assert_eq!(
                script_text(context, "String(Fusor.ops.op_add(20, 22));"),
                "42"
            );
            assert_eq!(
                script_text(context, "String(Fusor.ops.op_greet('fusor'));"),
                "hello fusor"
            );
            // OpError classes reach JavaScript as the named intrinsic family.
            assert_eq!(
                script_text(
                    context,
                    "var kind; try { Fusor.ops.op_fail(); } catch (error) { kind = error.name + ':' + error.message; } String(kind);",
                ),
                "RangeError:out of range"
            );
        });
    }

    #[test]
    fn argument_deserialization_failures_raise_parameter_indexed_type_errors() {
        with_context(|context| {
            install_namespace(context).expect("namespace");
            install_op(context, op_add::declaration(), op_add::call).expect("add");

            assert_eq!(
                script_text(
                    context,
                    "var kind, message;\
                     try { Fusor.ops.op_add('not a number', 1); }\
                     catch (error) { kind = error.name; message = error.message; }\
                     String(kind + '|' + message);",
                ),
                "TypeError|parameter 0: expected a Number, received String"
            );
            assert_eq!(
                script_text(
                    context,
                    "var kind, message;\
                     try { Fusor.ops.op_add(1); }\
                     catch (error) { kind = error.name; message = error.message; }\
                     String(kind + '|' + message);",
                ),
                "TypeError|parameter 1: missing argument"
            );
        });
    }

    #[op]
    fn op_with_context(context: &mut Context<'_>, offset: i32) -> Result<i32, OpError> {
        let global = context
            .global_object()
            .map_err(|error| OpError::new(error.to_string()))?
            .into_object()
            .map_err(|error| OpError::new(error.to_string()))?;
        let key = context
            .property_key("ctx_probe")
            .map_err(|error| OpError::new(error.to_string()))?;
        let value = global
            .get(context, key)
            .map_err(|error| OpError::new(error.to_string()))?;
        let base = value
            .as_i32()
            .map_err(|error| OpError::new(error.to_string()))?
            .unwrap_or(0);
        Ok(base + offset)
    }

    #[test]
    fn the_first_context_parameter_is_injected_and_not_a_js_argument() {
        // The context parameter is host glue, not a JavaScript argument:
        // the declaration lists only the JS-visible parameters.
        assert_eq!(op_with_context::declaration().parameter_types, &["i32"]);
        with_context(|context| {
            install_namespace(context).expect("namespace");
            install_op(
                context,
                op_with_context::declaration(),
                op_with_context::call,
            )
            .expect("op");
            assert_eq!(
                script_text(
                    context,
                    "globalThis.ctx_probe = 40; String(Fusor.ops.op_with_context(2));",
                ),
                "42"
            );
        });
    }

    #[test]
    fn installing_a_namespace_twice_is_idempotent_and_ops_accumulate() {
        with_context(|context| {
            install_namespace(context).expect("namespace");
            install_namespace(context).expect("namespace again");
            install_op(context, op_add::declaration(), op_add::call).expect("add");
            install_op(context, op_greet::declaration(), op_greet::call).expect("greet");
            assert_eq!(
                script_text(
                    context,
                    "String(Fusor.ops.op_add(1, 2) + '|' + Fusor.ops.op_greet('x'));"
                ),
                "3|hello x"
            );
        });
    }
}
